export const dynamic = 'force-dynamic';

// app/api/public/landing-pages/[slug]/comments/route.ts
// 랜딩페이지 댓글 API (로그인 불필요)

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { SESSION_COOKIE } from '@/lib/auth';

/**
 * POST: 랜딩페이지 댓글 생성
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> | { slug: string } }
) {
  try {
    const resolvedParams = await Promise.resolve(params);
    const slug = resolvedParams.slug;

    // 랜딩페이지 조회
    const landingPage = await prisma.landingPage.findFirst({
      where: {
        OR: [
          { slug },
          { id: isNaN(Number(slug)) ? -1 : Number(slug) },
        ],
        isActive: true,
        isPublic: true,
        commentEnabled: true,
      },
    });

    if (!landingPage) {
      return NextResponse.json(
        { ok: false, error: '랜딩페이지를 찾을 수 없거나 댓글이 비활성화되어 있습니다.' },
        { status: 404 }
      );
    }

    const body = await req.json();
    const { authorName, content, password } = body;

    // 필수 필드 검증
    if (!authorName || !content) {
      return NextResponse.json(
        { ok: false, error: '작성자 이름과 내용은 필수입니다.' },
        { status: 400 }
      );
    }

    if (authorName.trim().length === 0 || content.trim().length === 0) {
      return NextResponse.json(
        { ok: false, error: '작성자 이름과 내용을 입력해주세요.' },
        { status: 400 }
      );
    }

    // 비밀번호 검증 (일반 유저 댓글은 비밀번호 필수)
    if (!password || password.trim().length === 0) {
      return NextResponse.json(
        { ok: false, error: '비밀번호를 입력해주세요.' },
        { status: 400 }
      );
    }

    // 비밀번호 해시 (간단한 해시, 실제로는 bcrypt 사용 권장)
    const crypto = await import('crypto');
    const hashedPassword = crypto.createHash('sha256').update(password.trim()).digest('hex');

    // 세션에서 사용자 ID 가져오기 (있는 경우)
    const sid = req.cookies.get(SESSION_COOKIE)?.value;
    let userId: number | null = null;
    
    if (sid) {
      try {
        const session = await prisma.session.findUnique({
          where: { id: sid },
          select: {
            User: {
              select: {
                id: true,
              },
            },
          },
        });
        if (session?.User) {
          userId = session.User.id;
        }
      } catch (error) {
        console.error('[Landing Page Comment] Session check error:', error);
        // 세션 확인 실패는 무시 (비회원으로 처리)
      }
    }

    // 댓글 생성 (password와 userId는 metadata에 저장)
    const comment = await prisma.landingPageComment.create({
      data: {
        landingPageId: landingPage.id,
        authorName: authorName.trim(),
        content: content.trim(),
        metadata: { 
          password: hashedPassword,
          userId: userId, // 작성자 ID 저장 (있는 경우)
        },
        isAutoGenerated: false, // 일반 유저가 작성한 댓글
        createdAt: new Date(), // createdAt 필드 추가
      },
    });

    return NextResponse.json({
      ok: true,
      comment: {
        id: comment.id,
        authorName: comment.authorName,
        content: comment.content,
        createdAt: comment.createdAt.toISOString(),
      },
    });
  } catch (error: any) {
    console.error('[Landing Page Comment] Error:', error);
    return NextResponse.json(
      {
        ok: false,
        error: error.message || '댓글 작성 중 오류가 발생했습니다.',
      },
      { status: 500 }
    );
  }
}

/**
 * GET: 랜딩페이지 댓글 목록 조회
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string }> | { slug: string } }
) {
  try {
    const resolvedParams = await Promise.resolve(params);
    const slug = resolvedParams.slug;

    // 랜딩페이지 조회
    const landingPage = await prisma.landingPage.findFirst({
      where: {
        OR: [
          { slug },
          { id: isNaN(Number(slug)) ? -1 : Number(slug) },
        ],
        isActive: true,
        isPublic: true,
      },
    });

    if (!landingPage) {
      return NextResponse.json(
        { ok: false, error: '랜딩페이지를 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    // 세션에서 현재 사용자 ID 가져오기
    const sid = req.cookies.get(SESSION_COOKIE)?.value;
    let currentUserId: number | null = null;
    let currentUserRole: string | null = null;
    let isBossUser = false;
    
    if (sid) {
      try {
        const session = await prisma.session.findUnique({
          where: { id: sid },
          select: {
            User: {
              select: {
                id: true,
                role: true,
                name: true,
                email: true,
              },
            },
          },
        });
        if (session?.User) {
          currentUserId = session.User.id;
          currentUserRole = session.User.role;
          // boss로 시작하는 사용자명/이메일 체크
          const userName = (session.User.name || '').toLowerCase();
          const userEmail = (session.User.email || '').toLowerCase();
          isBossUser = userName.startsWith('boss') || userEmail.startsWith('boss');
        }
      } catch (error) {
        console.error('[Landing Page Comment] Session check error:', error);
        // 세션 확인 실패는 무시
      }
    }

    // 랜딩페이지 소유자 확인 (관리자 또는 대리점장)
    let isLandingPageOwner = false;
    if (currentUserId && landingPage.adminId === currentUserId) {
      // 본인이 만든 랜딩페이지인 경우, 관리자 또는 대리점장인지 확인
      try {
        const user = await prisma.user.findUnique({
          where: { id: currentUserId },
          include: {
            AffiliateProfile: {
              select: {
                type: true,
              },
            },
          },
        });
        
        // 관리자 또는 대리점장인 경우 소유자로 인정
        if (currentUserRole === 'admin' || user?.AffiliateProfile?.type === 'BRANCH_MANAGER') {
          isLandingPageOwner = true;
          console.log('[Landing Page Comment] Owner detected:', {
            userId: currentUserId,
            role: currentUserRole,
            affiliateType: user?.AffiliateProfile?.type,
            isOwner: true
          });
        }
      } catch (error) {
        console.error('[Landing Page Comment] Owner check error:', error);
      }
    }

    // 댓글 목록 조회
    const comments = await prisma.landingPageComment.findMany({
      where: {
        landingPageId: landingPage.id,
      },
      orderBy: {
        createdAt: 'desc',
      },
      take: 50,
    });

    return NextResponse.json({
      ok: true,
      comments: comments.map((comment) => {
        // 댓글 작성자 ID 확인
        let commentAuthorId: number | null = null;
        if (comment.metadata && typeof comment.metadata === 'object' && 'userId' in comment.metadata) {
          commentAuthorId = (comment.metadata as any).userId;
        }
        
        return {
          id: comment.id,
          authorName: comment.authorName,
          content: comment.content,
          createdAt: comment.createdAt.toISOString(),
          isAutoGenerated: comment.isAutoGenerated,
          isMine: currentUserId !== null && commentAuthorId === currentUserId, // 본인 댓글 여부
        };
      }),
      isLandingPageOwner, // 랜딩페이지 소유자 여부
      isBossUser, // boss 사용자 여부
    });
  } catch (error: any) {
    console.error('[Landing Page Comment] Error:', error);
    return NextResponse.json(
      {
        ok: false,
        error: error.message || '댓글 조회 중 오류가 발생했습니다.',
      },
      { status: 500 }
    );
  }
}
