import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Wo ist der Check-in-Schalter?', pronunciation: '(보 이스트 데르 첵인-샬터?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Kann ich einen Fensterplatz bekommen?', pronunciation: '(칸 이히 아이넨 펜스터플라츠 베콤멘?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Wie viel kostet zusätzliches Gepäck?', pronunciation: '(비 필 코스테트 추자츠리헤스 게펙?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Ich habe eine Reservierung unter dem Namen (Name)', pronunciation: '((이름) 나멘)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Kann ich ein zusätzliches Handtuch bekommen?', pronunciation: '(칸 이히 아인 추자츠리헤스 한트투흐 베콤멘?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'Wann wird das Frühstück serviert?', pronunciation: '(반 비르트 다스 프뤼스튀크 제르비르트?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Können Sie mein Gepäck nach dem Check-out aufbewahren?', pronunciation: '(쾨넌 지 마인 게펙 나흐 뎀 첵아웃 아우프베바렌?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Können Sie mein Gepäck vor dem Check-in aufbewahren?', pronunciation: '(쾨넌 지 마인 게펙 포르 뎀 첵인 아우프베바렌?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Das Wi-Fi funktioniert nicht in meinem Zimmer', pronunciation: '(다스 와이파이 풍크치오니르트 니히트 인 마이넴 치머)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'Die Klimaanlage funktioniert nicht', pronunciation: '(디 클리마안라게 풍크치오니르트 니히트)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'Das heiße Wasser funktioniert nicht', pronunciation: '(다스 하이서 바서르 풍크치오니르트 니히트)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Ist ein verspäteter Check-out möglich?', pronunciation: '(이스트 아인 페르슈페테터 첵아웃 뫼글리흐?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Können Sie ein Taxi für mich rufen?', pronunciation: '(쾨넌 지 아인 택시 퓌어 미히 루펜?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Kann ich die Speisekarte sehen?', pronunciation: '(칸 이히 디 슈파이제카르테 제헨?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Ich möchte (Gerichtname) bestellen', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Wasser, bitte', pronunciation: '(바서르, 비테)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Kann ich die Rechnung haben?', pronunciation: '(칸 이히 디 레히눙 하벤?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Was ist das beliebteste Gericht hier?', pronunciation: '(바스 이스트 다스 벨리프테스테 게리히트 히어?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Was empfehlen Sie?', pronunciation: '(바스 엠프펠렌 지?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Ich bin allergisch gegen Nüsse', pronunciation: '(이히 빈 알레르기쉬 게겐 뉘서)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Enthält dies Erdnüsse?', pronunciation: '(엔텔트 디스 에르트뉘서?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Kann ich das zum Mitnehmen bekommen?', pronunciation: '(칸 이히 다스 쭘 미트네멘 베콤멘?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Können wir separate Rechnungen haben?', pronunciation: '(쾨넌 비어 제파라테 레히눙엔 하벤?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Wie viel kostet das?', pronunciation: '(비 필 코스테트 다스?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Haben Sie das in einer anderen Größe?', pronunciation: '(하벤 지 다스 인 아이너 안데렌 그뢰서?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Kann ich mit Karte bezahlen?', pronunciation: '(칸 이히 미트 카르테 베찰렌?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Kann ich eine Rückerstattung bekommen?', pronunciation: '(칸 이히 아이네 뤼크에르슈타퉁 베콤멘?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Wo ist die Bushaltestelle?', pronunciation: '(보 이스트 디 부스할테슈텔레?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Wie komme ich zum Bahnhof?', pronunciation: '(비 코메 이히 쭘 반호프?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Ist es weit?', pronunciation: '(이스트 에스 바이트?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Kann ich eine Karte bekommen?', pronunciation: '(칸 이히 아이네 카르테 베콤멘?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Wo ist die nächste U-Bahn-Station?', pronunciation: '(보 이스트 디 넥스테 우-반-스타시온?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Zwei Erwachsene und ein Kind, bitte', pronunciation: '(츠바이 에르바흐세네 운트 아인 키인트, 비테)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'Wann öffnet es?', pronunciation: '(반 외프네트 에스?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'Wann schließt es?', pronunciation: '(반 슐리스트 에스?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Ist es erlaubt, hier Fotos zu machen?', pronunciation: '(이스트 에스 에를라우프트, 히어 포토스 추 마헨?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Ich fühle mich nicht wohl', pronunciation: '(이히 퓔레 미히 니히트 볼)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Ich brauche einen Arzt', pronunciation: '(이히 브라우헤 아이넨 아르츠트)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Ich habe Kopfschmerzen', pronunciation: '(이히 하베 코프슈메르첸)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Bitte rufen Sie die Polizei', pronunciation: '(비테 루펜 지 디 폴리차이)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Ich habe meinen Reisepass verloren', pronunciation: '(이히 하베 마이넨 라이제파스 페를로렌)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Ich habe meine Brieftasche verloren', pronunciation: '(이히 하베 마이네 브리프타셰 페를로렌)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Ich habe mein Handy verloren', pronunciation: '(이히 하베 마인 한디 페를로렌)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Wo ist das Fundbüro?', pronunciation: '(보 이스트 다스 푼트뷰로?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Können Sie das für mich aufschreiben?', pronunciation: '(쾨넌 지 다스 퓌어 미히 아우프슈라이벤?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Bitte sprechen Sie langsamer', pronunciation: '(비테 슈프레헨 지 랑자머)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Wo ist die nächste Apotheke?', pronunciation: '(보 이스트 디 넥스테 아포테케?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Ich brauche etwas gegen Kopfschmerzen', pronunciation: '(이히 브라우헤 에트바스 게겐 코프슈메르첸)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Ich brauche etwas gegen Bauchschmerzen', pronunciation: '(이히 브라우헤 에트바스 게겐 바우흐슈메르첸)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Ich brauche etwas gegen eine Erkältung', pronunciation: '(이히 브라우헤 에트바스 게겐 아이네 에르켈퉁)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Haben Sie Pflaster?', pronunciation: '(하벤 지 프플라스터?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Wo ist meine Kabine?', pronunciation: '보 이스트 마이네 카비네?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Mein Gepäck ist noch nicht angekommen', pronunciation: '마인 게펙 이스트 노흐 니히트 앙게콤멘', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Wo ist die Sicherheitsübung?', pronunciation: '보 이스트 디 지허하이츠위붕?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'Um wie viel Uhr muss ich zum Schiff zurückkehren?', pronunciation: '움 비 필 우르 무스 이히 쭘 시프 추뤽케렌?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Wie spät ist es jetzt auf dem Schiff?', pronunciation: '비 슈펫 이스트 에스 예츠트 아우프 뎀 시프?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Wo ist das medizinische Zentrum?', pronunciation: '보 이스트 다스 메디친이셰 첸트룸?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Kann ich Medikamente gegen Seekrankheit bekommen?', pronunciation: '칸 이히 메디카멘테 게겐 제크란크하이트 베콤멘?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'Ich habe meine Kabinenkarte (Kabinenschlüssel) verloren', pronunciation: '이히 하베 마이네 카비넨카르테 (카비넨슐뤼설) 페를로렌', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Wo ist das Buffet-Restaurant?', pronunciation: '보 이스트 다스 부페이-레스토랑?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Wie spät ist meine Abendessenszeit und mein Tisch?', pronunciation: '비 슈펫 이스트 마이네 아벤데센스차이트 운트 마인 티시?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Kann ich Zimmerservice bestellen?', pronunciation: '칸 이히 치머세르비스 베슈텔렌?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Ich möchte das (italienische) Restaurant reservieren', pronunciation: '이히 뫼히테 다스 (이탈리니셰) 레스토랑 레제르비렌', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Wo kann ich das Tagesprogramm bekommen?', pronunciation: '보 칸 이히 다스 타게스프로그람 베콤멘?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Ich möchte diese Landausflug buchen', pronunciation: '이히 뫼히테 디제 란다우스플루크 부헌', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Wo ist der Treffpunkt für die Tour?', pronunciation: '보 이스트 데르 트레프푼크 퓌어 디 투어?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Wie verbinde ich mich mit dem Wi-Fi?', pronunciation: '비 페르빈데 이히 미히 미트 뎀 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Ist das inklusive (kostenlos)?', pronunciation: '이스트 다스 인클루지베 (코스텐로스)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Können Sie bitte meine Kabine sauber machen?', pronunciation: '쾨넌 지 비테 마이네 카비네 자우버 마헨?', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'Der Safe in meiner Kabine funktioniert nicht', pronunciation: '데르 자페 인 마이너 카비네 풍크치오니르트 니히트', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Wo ist der nächste Aufzug?', pronunciation: '보 이스트 데르 넥스테 아우프추크?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Sprechen Sie Englisch?', pronunciation: '(슈프레헨 지 잉글리쉬?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Wo ist die Toilette?', pronunciation: '(보 이스트 디 토일레테?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Kann ich das anprobieren?', pronunciation: '(칸 이히 다스 안프로비렌?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Danke', pronunciation: '(단케)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Bitte sprechen Sie langsamer', pronunciation: '(비테 슈프레헨 지 랑자머)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
