import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Where is the check-in counter?', pronunciation: '(웨어 이즈 더 체크인 카운터?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Can I have a window seat, please?', pronunciation: '(캔 아이 해브 어 윈도우 싯, 플리즈?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'How much does it cost to check an extra bag?', pronunciation: '(하우 머치 더즈 잇 코스트 투 체크 언 엑스트라 백?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'I have a reservation under the name (name)', pronunciation: '(아이 해브 어 레저베이션 언더 더 네임 (이름))', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Could I get an extra towel, please?', pronunciation: '(쿠드 아이 겟 언 엑스트라 타월, 플리즈?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'What time is breakfast served?', pronunciation: '(왓 타임 이즈 브렉퍼스트 서브드?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Could you keep my luggage after I check out?', pronunciation: '(쿠드 유 킵 마이 러기지 애프터 아이 체크 아웃?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Could you keep my luggage before I check in?', pronunciation: '(쿠드 유 킵 마이 러기지 비포 아이 체크 인?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'The Wi-Fi isn\'t working in my room', pronunciation: '(더 와이파이 이즌트 워킹 인 마이 룸)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'The air conditioner isn\'t working', pronunciation: '(디 에어 컨디셔너 이즌트 워킹)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'The hot water isn\'t working', pronunciation: '(더 핫 워터 이즌트 워킹)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Is it possible to get a late check-out?', pronunciation: '(이즈 잇 파서블 투 겟 어 레이트 체크아웃?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Could you call a taxi for me, please?', pronunciation: '(쿠드 유 콜 어 택시 포 미, 플리즈?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Can I see the menu, please?', pronunciation: '(캔 아이 씨 더 메뉴, 플리즈?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'I would like to order (음식 이름)', pronunciation: '(아이 우드 라이크 투 오더 (음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Water, please', pronunciation: '(워터, 플리즈)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Can I have the bill, please?', pronunciation: '(캔 아이 해브 더 빌, 플리즈?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'What\'s the most popular dish here?', pronunciation: '(왓츠 더 모스트 파퓰러 디시 히어?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'What would you recommend?', pronunciation: '(왓 우드 유 레코멘드?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'I have an allergy to nuts', pronunciation: '(아이 해브 언 앨러지 투 넛츠)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Does this contain peanuts?', pronunciation: '(더즈 디스 컨테인 피넛츠?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Can I get this to go?', pronunciation: '(캔 아이 겟 디스 투 고?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Could we have separate bills?', pronunciation: '(쿠드 위 해브 세퍼레이트 빌즈?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'How much is this?', pronunciation: '(하우 머치 이즈 디스?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Do you have this in a different size?', pronunciation: '(두 유 해브 디스 인 어 디퍼런트 사이즈?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Can I pay by card?', pronunciation: '(캔 아이 페이 바이 카드?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Can I get a refund?', pronunciation: '(캔 아이 겟 어 리펀드?)', emoji: '↩️' },
      { ko: '이거 다른 색상 있나요?', target: 'Do you have this in a different color?', pronunciation: '(두 유 해브 디스 인 어 디퍼런트 컬러?)', emoji: '🎨' },
      { ko: '이거 입어봐도 될까요?', target: 'Can I try this on?', pronunciation: '(캔 아이 트라이 디스 온?)', emoji: '👕' },
      { ko: '할인 있나요?', target: 'Is there a discount?', pronunciation: '(이즈 데어 어 디스카운트?)', emoji: '🏷️' },
      { ko: '포장해 주세요', target: 'Please wrap it up', pronunciation: '(플리즈 랩 잇 업)', emoji: '📦' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Excuse me, where is the bus stop?', pronunciation: '(익스큐즈 미, 웨어 이즈 더 버스 스탑?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'How can I get to the station?', pronunciation: '(하우 캔 아이 겟 투 더 스테이션?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Is it far?', pronunciation: '(이즈 잇 파?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Could I get a map?', pronunciation: '(쿠드 아이 겟 어 맵?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Where is the nearest subway station?', pronunciation: '(웨어 이즈 더 니어리스트 서브웨이 스테이션?)', emoji: '🚇' },
      { ko: '택시 타는 곳이 어디인가요?', target: 'Where can I get a taxi?', pronunciation: '(웨어 캔 아이 겟 어 택시?)', emoji: '🚕' },
      { ko: '공항까지 어떻게 가나요?', target: 'How do I get to the airport?', pronunciation: '(하우 두 아이 겟 투 더 에어포트?)', emoji: '✈️' },
      { ko: '이 주소로 가주세요', target: 'Please take me to this address', pronunciation: '(플리즈 테이크 미 투 디스 어드레스)', emoji: '📍' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Two adults and one child, please', pronunciation: '(투 어덜츠 앤 원 차일드, 플리즈)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'What time does it open?', pronunciation: '(왓 타임 더즈 잇 오픈?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'What time does it close?', pronunciation: '(왓 타임 더즈 잇 클로즈?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Is it okay to take a picture here?', pronunciation: '(이즈 잇 오케이 투 테이크 어 픽처 히어?)', emoji: '📷' },
      { ko: '티켓 한 장 주세요', target: 'One ticket, please', pronunciation: '(원 티켓, 플리즈)', emoji: '🎫' },
      { ko: '가이드 투어 있나요?', target: 'Do you have a guided tour?', pronunciation: '(두 유 해브 어 가이디드 투어?)', emoji: '👨‍🏫' },
      { ko: '입장료는 얼마인가요?', target: 'How much is the admission fee?', pronunciation: '(하우 머치 이즈 더 어드미션 피?)', emoji: '💵' },
      { ko: '이곳의 유명한 명소가 뭔가요?', target: 'What are the famous attractions here?', pronunciation: '(왓 아 더 페이머스 어트랙션즈 히어?)', emoji: '⭐' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'I don\'t feel well', pronunciation: '(아이 돈 필 웰)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'I need a doctor', pronunciation: '(아이 니드 어 닥터)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'I have a headache', pronunciation: '(아이 해브 어 헤드에이크)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Please call the police', pronunciation: '(플리즈 콜 더 폴리스)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'I seem to have lost my passport', pronunciation: '(아이 심 투 해브 로스트 마이 패스포트)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'I seem to have lost my wallet', pronunciation: '(아이 심 투 해브 로스트 마이 월렛)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'I seem to have lost my phone', pronunciation: '(아이 심 투 해브 로스트 마이 폰)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Where is the lost and found?', pronunciation: '(웨어 이즈 더 로스트 앤 파운드?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Could you write that down for me, please?', pronunciation: '(쿠드 유 라이트 댓 다운 포 미, 플리즈?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Please speak more slowly', pronunciation: '(플리즈 스피크 모어 슬로울리)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Where is the nearest pharmacy?', pronunciation: '(웨어 이즈 더 니어리스트 파머시?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'I need something for a headache', pronunciation: '(아이 니드 섬띵 포 어 헤드에이크)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'I need something for a stomachache', pronunciation: '(아이 니드 섬띵 포 어 스토머케이크)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'I need something for a cold', pronunciation: '(아이 니드 섬띵 포 어 콜드)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Do you have band-aids?', pronunciation: '(두 유 해브 밴드-에이즈?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Where is my stateroom?', pronunciation: '웨어 이즈 마이 스테이트룸?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'My luggage hasn\'t arrived yet', pronunciation: '마이 러기지 해즌트 어라이브드 엣', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Where is the safety drill?', pronunciation: '웨어 이즈 더 세이프티 드릴?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'What time do I need to be back on the ship?', pronunciation: '왓 타임 두 아이 니드 투 비 백 온 더 쉽?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'What is the ship\'s time now?', pronunciation: '왓 이즈 더 쉽스 타임 나우?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Where is the medical center?', pronunciation: '웨어 이즈 더 메디컬 센터?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Can I get some medicine for seasickness?', pronunciation: '캔 아이 겟 섬 메디슨 포 씨시크니스?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'I lost my ship card (room key)', pronunciation: '아이 로스트 마이 쉽 카드 (룸 키)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Where is the buffet restaurant?', pronunciation: '웨어 이즈 더 부페이 레스토랑?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'What is my assigned dining time and table?', pronunciation: '왓 이즈 마이 어사인드 다이닝 타임 앤 테이블?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Can I order room service?', pronunciation: '캔 아이 오더 룸 서비스?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'I\'d like to book the (Italian) restaurant', pronunciation: '아이드 라이크 투 북 더 (이탈리안) 레스토랑', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Where can I get the daily schedule?', pronunciation: '웨어 캔 아이 겟 더 데일리 스케줄?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'I\'d like to book this shore excursion', pronunciation: '아이드 라이크 투 북 디스 쇼어 익스커션', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Where is the meeting point for the tour?', pronunciation: '웨어 이즈 더 미팅 포인트 포 더 투어?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'How do I connect to the Wi-Fi?', pronunciation: '하우 두 아이 커넥트 투 더 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Is this included (free)?', pronunciation: '이즈 디스 인클루디드 (프리)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Please make up my room', pronunciation: '플리즈 메이크 업 마이 룸', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'The safe in my room isn\'t working', pronunciation: '더 세이프 인 마이 룸 이즌트 워킹', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Where is the nearest elevator?', pronunciation: '웨어 이즈 더 니어리스트 엘리베이터?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Do you speak English?', pronunciation: '(두 유 스피크 잉글리시?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Where is the bathroom?', pronunciation: '(웨어 이즈 더 배스룸?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Can I try this on?', pronunciation: '(캔 아이 트라이 디스 온?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Thank you', pronunciation: '(땡큐)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Please speak slowly', pronunciation: '(플리즈 스피크 슬로울리)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
