import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: '¿Dónde está el mostrador de facturación?', pronunciation: '(동데 에스타 엘 모스트라도르 데 팍투라시온?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: '¿Puedo tener un asiento junto a la ventana?', pronunciation: '(푸에도 테네르 운 아시엔토 훈토 아 라 벤타나?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: '¿Cuánto cuesta facturar un equipaje adicional?', pronunciation: '(쿠안토 쿠에스타 팍투라르 운 에키파헤 아디시오날?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Tengo una reserva a nombre de (nombre)', pronunciation: '((이름) 놈브레)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: '¿Puedo tener una toalla adicional?', pronunciation: '(푸에도 테네르 우나 토아야 아디시오날?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: '¿A qué hora se sirve el desayuno?', pronunciation: '(아 케 오라 세 시르베 엘 데사유노?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: '¿Pueden guardar mi equipaje después del check-out?', pronunciation: '(푸에덴 구아르다르 미 에키파헤 데스푸에스 델 첵아웃?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: '¿Pueden guardar mi equipaje antes del check-in?', pronunciation: '(푸에덴 구아르다르 미 에키파헤 안테스 델 첵인?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'El Wi-Fi no funciona en mi habitación', pronunciation: '(엘 와이파이 노 푼시오나 엔 미 아비타시온)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'El aire acondicionado no funciona', pronunciation: '(엘 아이레 아콘디시오나도 노 푼시오나)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'El agua caliente no funciona', pronunciation: '(엘 아과 칼리엔테 노 푼시오나)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: '¿Es posible tener un check-out tardío?', pronunciation: '(에스 포시블 테네르 운 첵아웃 타르디오?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: '¿Pueden llamar un taxi para mí?', pronunciation: '(푸에덴 야마르 운 택시 파라 미?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: '¿Puedo ver el menú?', pronunciation: '(푸에도 베르 엘 메누?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Me gustaría pedir (nombre del plato)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Agua, por favor', pronunciation: '(아과, 포르 파보르)', emoji: '💧' },
      { ko: '계산서 주세요', target: '¿Puedo tener la cuenta?', pronunciation: '(푸에도 테네르 라 쿠엔타?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: '¿Cuál es el plato más popular aquí?', pronunciation: '(쿠알 에스 엘 플라토 마스 포풀라르 아키?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: '¿Qué recomienda?', pronunciation: '(케 레코미엔다?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Soy alérgico a los frutos secos', pronunciation: '(소이 알레르히코 아 로스 프루토스 세코스)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: '¿Esto contiene cacahuetes?', pronunciation: '(에스토 콘티엔네 카카우에테스?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: '¿Puedo llevar esto para llevar?', pronunciation: '(푸에도 예바르 에스토 파라 예바르?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: '¿Podemos tener cuentas separadas?', pronunciation: '(포데모스 테네르 쿠엔타스 세파라다스?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: '¿Cuánto cuesta esto?', pronunciation: '(쿠안토 쿠에스타 에스토?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: '¿Tienen esto en otra talla?', pronunciation: '(티에넨 에스토 엔 오트라 타야?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: '¿Puedo pagar con tarjeta?', pronunciation: '(푸에도 파가르 콘 타르헤타?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: '¿Puedo obtener un reembolso?', pronunciation: '(푸에도 옵테네르 운 레엠볼소?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: '¿Dónde está la parada de autobús?', pronunciation: '(동데 에스타 라 파라다 데 아우토부스?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: '¿Cómo puedo llegar a la estación?', pronunciation: '(코모 푸에도 예가르 아 라 에스타시온?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: '¿Está lejos?', pronunciation: '(에스타 레호스?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: '¿Puedo tener un mapa?', pronunciation: '(푸에도 테네르 운 마파?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: '¿Dónde está la estación de metro más cercana?', pronunciation: '(동데 에스타 라 에스타시온 데 메트로 마스 세르카나?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Dos adultos y un niño, por favor', pronunciation: '(도스 아둘토스 이 운 니뇨, 포르 파보르)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: '¿A qué hora abre?', pronunciation: '(아 케 오라 아브레?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: '¿A qué hora cierra?', pronunciation: '(아 케 오라 시에라?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: '¿Está permitido tomar fotos aquí?', pronunciation: '(에스타 페르미티도 토마르 포토스 아키?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'No me siento bien', pronunciation: '(노 메 시엔토 비엔)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Necesito un médico', pronunciation: '(네세시토 운 메디코)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Tengo dolor de cabeza', pronunciation: '(텐고 돌로르 데 카베사)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Por favor, llame a la policía', pronunciation: '(포르 파보르, 야메 아 라 폴리시아)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Creo que he perdido mi pasaporte', pronunciation: '(크레오 케 에 페르디도 미 파사포르테)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Creo que he perdido mi cartera', pronunciation: '(크레오 케 에 페르디도 미 카르테라)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Creo que he perdido mi teléfono', pronunciation: '(크레오 케 에 페르디도 미 텔레포노)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: '¿Dónde está la oficina de objetos perdidos?', pronunciation: '(동데 에스타 라 오피시나 데 옵헤토스 페르디도스?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: '¿Puede escribirlo para mí?', pronunciation: '(푸에데 에스크리빌로 파라 미?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Por favor, hable más despacio', pronunciation: '(포르 파보르, 아블레 마스 데스파시오)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: '¿Dónde está la farmacia más cercana?', pronunciation: '(동데 에스타 라 파르마시아 마스 세르카나?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Necesito algo para el dolor de cabeza', pronunciation: '(네세시토 알고 파라 엘 돌로르 데 카베사)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Necesito algo para el dolor de estómago', pronunciation: '(네세시토 알고 파라 엘 돌로르 데 에스토마고)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Necesito algo para el resfriado', pronunciation: '(네세시토 알고 파라 엘 레스프리아도)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: '¿Tienen tiritas?', pronunciation: '(티에넨 티리타스?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: '¿Dónde está mi camarote?', pronunciation: '동데 에스타 미 카마로테?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Mi equipaje aún no ha llegado', pronunciation: '미 에키파헤 아운 노 아 예가도', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: '¿Dónde está el simulacro de seguridad?', pronunciation: '동데 에스타 엘 시물라크로 데 세구리다드?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: '¿A qué hora necesito volver al barco?', pronunciation: '아 케 오라 네세시토 볼베르 알 바르코?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: '¿Qué hora es en el barco ahora?', pronunciation: '케 오라 에스 엔 엘 바르코 아오라?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: '¿Dónde está el centro médico?', pronunciation: '동데 에스타 엘 센트로 메디코?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: '¿Puedo obtener medicina para el mareo?', pronunciation: '푸에도 옵테네르 메디시나 파라 엘 마레오?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'He perdido mi tarjeta de camarote (llave de camarote)', pronunciation: '에 페르디도 미 타르헤타 데 카마로테 (야베 데 카마로테)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: '¿Dónde está el restaurante buffet?', pronunciation: '동데 에스타 엘 레스타우란테 부페이?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: '¿Cuál es mi hora y mesa para la cena?', pronunciation: '쿠알 에스 미 오라 이 메사 파라 라 세나?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: '¿Puedo pedir servicio a la habitación?', pronunciation: '푸에도 페디르 세르비시오 아 라 아비타시온?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Me gustaría reservar el restaurante (italiano)', pronunciation: '메 구스타리아 레세르바르 엘 레스타우란테 (이탈리아노)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: '¿Dónde puedo obtener el programa diario?', pronunciation: '동데 푸에도 옵테네르 엘 프로그라마 디아리오?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Me gustaría reservar esta excursión en tierra', pronunciation: '메 구스타리아 레세르바르 에스타 엑스쿠르시온 엔 티에라', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: '¿Dónde está el punto de encuentro para la excursión?', pronunciation: '동데 에스타 엘 푼토 데 엔쿠엔트로 파라 라 엑스쿠르시온?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: '¿Cómo me conecto al Wi-Fi?', pronunciation: '코모 메 코넥토 알 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: '¿Esto está incluido (gratis)?', pronunciation: '에스토 에스타 인클루이도 (그라티스)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Por favor, limpie mi habitación', pronunciation: '포르 파보르, 림피에 미 아비타시온', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'La caja fuerte de mi habitación no funciona', pronunciation: '라 카하 푸에르테 데 미 아비타시온 노 푼시오나', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: '¿Dónde está el ascensor más cercano?', pronunciation: '동데 에스타 엘 아센소르 마스 세르카노?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: '¿Habla inglés?', pronunciation: '(아블라 잉글레스?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: '¿Dónde está el baño?', pronunciation: '(동데 에스타 엘 바뇨?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: '¿Puedo probármelo?', pronunciation: '(푸에도 프로바르멜로?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Gracias', pronunciation: '(그라시아스)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Por favor, hable más despacio', pronunciation: '(포르 파보르, 아블레 마스 데스파시오)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
