import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Où se trouve le comptoir d\'enregistrement?', pronunciation: '(우 스 트루브 르 콩투아르 랑제스트르망?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Puis-je avoir un siège côté fenêtre?', pronunciation: '(퓌-주 아부아르 운 시에주 코테 페네트르?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Combien coûte l\'enregistrement d\'un bagage supplémentaire?', pronunciation: '(콩비앙 쿠트 랑제스트르망 뒤 밧가지 쉬플레멘테르?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'J\'ai une réservation au nom de (nom)', pronunciation: '((이름) 놈)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Puis-je avoir une serviette supplémentaire?', pronunciation: '(퓌-주 아부아르 운 세르비에트 쉬플레멘테르?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'À quelle heure le petit-déjeuner est-il servi?', pronunciation: '(아 켈 외르 르 뻬티-데즈외네 에-틸 세르비?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Pouvez-vous garder mes bagages après le check-out?', pronunciation: '(부베-부 가르데 메 바가지 아프레 르 첵아웃?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Pouvez-vous garder mes bagages avant le check-in?', pronunciation: '(부베-부 가르데 메 바가지 아방 르 첵인?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Le Wi-Fi ne fonctionne pas dans ma chambre', pronunciation: '(르 와이파이 느 평시오느 파 당 마 샹브르)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'La climatisation ne fonctionne pas', pronunciation: '(라 클리마티자시옹 느 평시오느 파)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'L\'eau chaude ne fonctionne pas', pronunciation: '(로 쇼드 느 평시오느 파)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Est-il possible d\'avoir un check-out tardif?', pronunciation: '(에-틸 파시블 다부아르 운 첵아웃 타르디프?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Pouvez-vous appeler un taxi pour moi?', pronunciation: '(부베-부 아펠레 운 택시 푸르 모아?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Puis-je voir le menu?', pronunciation: '(퓌-주 부아르 르 머뉴?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Je voudrais commander (nom du plat)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'De l\'eau, s\'il vous plaît', pronunciation: '(드 로, 실 부 플레)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Puis-je avoir l\'addition?', pronunciation: '(퓌-주 아부아르 라디시옹?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Quel est le plat le plus populaire ici?', pronunciation: '(켈 에 르 플라 르 플뤼 포풀레르 이시?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Que recommandez-vous?', pronunciation: '(퀘 레코망데-부?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Je suis allergique aux noix', pronunciation: '(주 쉬이 알레르지크 오 누아)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Est-ce que cela contient des arachides?', pronunciation: '(에스 퀘 셀라 콩티앙 데 자라시드?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Puis-je emporter cela?', pronunciation: '(퓌-주 앙포르테 셀라?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Pouvons-nous avoir des additions séparées?', pronunciation: '(부봉-누 아부아르 데 자디시옹 세파레?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Combien cela coûte-t-il?', pronunciation: '(콩비앙 셀라 쿠트-틸?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Avez-vous cela dans une autre taille?', pronunciation: '(아베-부 셀라 당 운 오트르 타이?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Puis-je payer par carte?', pronunciation: '(퓌-주 페이에 파르 카르트?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Puis-je obtenir un remboursement?', pronunciation: '(퓌-주 옵테니르 운 랑부르스망?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Où se trouve l\'arrêt de bus?', pronunciation: '(우 스 트루브 라레 드 뷔스?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Comment puis-je aller à la gare?', pronunciation: '(코망 퓌-주 알레 아 라 가르?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Est-ce loin?', pronunciation: '(에스 로앙?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Puis-je avoir une carte?', pronunciation: '(퓌-주 아부아르 운 카르트?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Où se trouve la station de métro la plus proche?', pronunciation: '(우 스 트루브 라 스타시옹 드 메트로 라 플뤼 프로슈?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Deux adultes et un enfant, s\'il vous plaît', pronunciation: '(되 자듈트 에 운 앙팡, 실 부 플레)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'À quelle heure ouvre-t-il?', pronunciation: '(아 켈 외르 우브르-틸?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'À quelle heure ferme-t-il?', pronunciation: '(아 켈 외르 페르므-틸?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Est-il permis de prendre des photos ici?', pronunciation: '(에-틸 페르미 드 트랑드레 데 포토 이시?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Je ne me sens pas bien', pronunciation: '(주 느 므 상 파 비앙)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'J\'ai besoin d\'un médecin', pronunciation: '(제 부주앙 뒤 메드생)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'J\'ai mal à la tête', pronunciation: '(제 말 아 라 테트)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Appelez la police, s\'il vous plaît', pronunciation: '(아펠레 라 폴리스, 실 부 플레)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'J\'ai semble avoir perdu mon passeport', pronunciation: '(제 상블 아부아르 페르뒤 몽 파스포르)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'J\'ai semble avoir perdu mon portefeuille', pronunciation: '(제 상블 아부아르 페르뒤 몽 포르트푸이)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'J\'ai semble avoir perdu mon téléphone', pronunciation: '(제 상블 아부아르 페르뒤 몽 텔레폰)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Où se trouve le bureau des objets trouvés?', pronunciation: '(우 스 트루브 르 뷔로 데 옵제 트루베?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Pouvez-vous l\'écrire pour moi?', pronunciation: '(부베-부 레크리르 푸르 모아?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Parlez plus lentement, s\'il vous plaît', pronunciation: '(파르레 플뤼 랑트망, 실 부 플레)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Où se trouve la pharmacie la plus proche?', pronunciation: '(우 스 트루브 라 파르마시 라 플뤼 프로슈?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'J\'ai besoin de quelque chose pour un mal de tête', pronunciation: '(제 부주앙 드 켈퀴 쇼즈 푸르 운 말 드 테트)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'J\'ai besoin de quelque chose pour un mal d\'estomac', pronunciation: '(제 부주앙 드 켈퀴 쇼즈 푸르 운 말 데스토마크)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'J\'ai besoin de quelque chose pour un rhume', pronunciation: '(제 부주앙 드 켈퀴 쇼즈 푸르 운 르므)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Avez-vous des pansements?', pronunciation: '(아베-부 데 팡스망?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Où se trouve ma cabine?', pronunciation: '우 스 트루브 마 카빈?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Mes bagages ne sont pas encore arrivés', pronunciation: '메 바가즈 느 쏜 파 장코르 아리베', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Où est l\'exercice de sécurité?', pronunciation: '우 에 렉세르시스 드 세퀴리테?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'À quelle heure dois-je revenir au navire?', pronunciation: '아 켈 외르 두아-주 르브니르 오 나비르?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Quelle est l\'heure du navire maintenant?', pronunciation: '켈 에 루어 뒤 나비르 망트낭?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Où se trouve le centre médical?', pronunciation: '우 스 트루브 르 셍트르 메디칼?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Puis-je avoir des médicaments contre le mal de mer?', pronunciation: '퓌-주 아부아르 데 메디카망 콩트르 르 말 드 메르?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'J\'ai perdu ma carte de cabine (clé de cabine)', pronunciation: '제 페르뒤 마 카르트 드 카빈 (클레 드 카빈)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Où se trouve le restaurant buffet?', pronunciation: '우 스 트루브 르 레스토랑 뷔페?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Quel est mon heure et ma table pour le dîner?', pronunciation: '켈 에 몽 외르 에 마 타블 푸르 르 디네?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Puis-je commander le service en chambre?', pronunciation: '퓌-주 코망데 르 세르비스 앙 샹브르?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Je voudrais réserver au restaurant (italien)', pronunciation: '주 부드레 레제르베 오 레스토랑 (이탈리앙)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Où puis-je obtenir le programme quotidien?', pronunciation: '우 퓌-주 옵테니르 르 프로그람 코티디앙?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Je voudrais réserver cette excursion à terre', pronunciation: '주 부드레 레제르베 셋 엑스퀴르시옹 아 테르', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Où est le point de rendez-vous pour la visite?', pronunciation: '우 에 르 푸앙 드 랑데-부 푸르 라 비지트?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Comment puis-je me connecter au Wi-Fi?', pronunciation: '코망 퓌-주 므 코넥테 오 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Est-ce inclus (gratuit)?', pronunciation: '에스-클 룽클루 (그라퇴이)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Pouvez-vous faire le ménage dans ma chambre?', pronunciation: '부베-부 페르 르 메나주 당 마 샹브르?', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'Le coffre-fort de ma chambre ne fonctionne pas', pronunciation: '르 코프르-포르 드 마 샹브르 느 평시오느 파', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Où est l\'ascenseur le plus proche?', pronunciation: '우 에 라센스외르 르 플뤼 프로슈?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Parlez-vous anglais?', pronunciation: '(파르레-부 앙글레?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Où sont les toilettes?', pronunciation: '(우 송 레 투알레트?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Puis-je essayer cela?', pronunciation: '(퓌-주 에세이에 셀라?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Merci', pronunciation: '(메르시)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Parlez plus lentement', pronunciation: '(파르레 플뤼 랑트망)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
