import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Di mana meja check-in?', pronunciation: '(디 마나 메자 첵인?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Tolong beri saya kursi dekat jendela', pronunciation: '(톨롱 베리 사야 쿠르시 데캇 젠델라)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Berapa biaya bagasi tambahan?', pronunciation: '(베라파 비아야 바가시 탐바한?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Saya sudah memesan atas nama (nama)', pronunciation: '((이름) 나마)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Bisakah saya mendapatkan handuk tambahan?', pronunciation: '(비사카 사야 므느다팟 한두크 탐바한?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'Jam berapa sarapan disajikan?', pronunciation: '(잠 베라파 사라판 디사지칸?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Bisakah Anda menyimpan bagasi saya setelah saya check-out?', pronunciation: '(비사카 안다 므니판 바가시 사야 세타파 사야 첵아웃?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Saya tiba lebih awal dari jam check-in, bisakah menyimpan bagasi?', pronunciation: '(사야 티바 레비히 아왈 다리 잠 첵인, 비사카 므니판 바가시?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Wi-Fi di kamar saya tidak berfungsi', pronunciation: '(와이파이 디 카마르 사야 티닥 베르푱시)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'AC tidak berfungsi', pronunciation: '(아체 티닥 베르푱시)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'Air panas tidak keluar', pronunciation: '(아이르 파나스 티닥 케루아르)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Bisakah check-out terlambat?', pronunciation: '(비사카 첵아웃 터르람바트?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Bisakah memanggil taksi untuk saya?', pronunciation: '(비사카 므망길 탁시 운투크 사야?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Bisakah saya melihat menu?', pronunciation: '(비사카 사야 멀리앗 메뉴?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Saya ingin memesan (nama makanan)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Tolong air', pronunciation: '(톨롱 아이르)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Bisakah saya mendapat tagihan?', pronunciation: '(비사카 사야 므느다팟 타기한?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Apa hidangan paling populer di sini?', pronunciation: '(아파 히당안 팔링 포풀레르 디 시니?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Apa yang Anda rekomendasikan?', pronunciation: '(아파 양 안다 레코멘디시칸?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Saya alergi terhadap kacang-kacangan', pronunciation: '(사야 알레르기 터르하답 카창-카창안)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Apakah ini mengandung kacang tanah?', pronunciation: '(아파카 이니 망구봉 카창 타나흐?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Bisakah dibawa pulang?', pronunciation: '(비사카 디바와 풀랑?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Bisakah tagihan dipisahkan?', pronunciation: '(비사카 타기한 디피사칸?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Berapa harga ini?', pronunciation: '(베라파 하르가 이니?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Apakah ada ukuran lain?', pronunciation: '(아파카 아다 우쿠란 라인?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Bisakah membayar dengan kartu?', pronunciation: '(비사카 므음바야르 드응안 카르투?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Bisakah mendapat pengembalian uang?', pronunciation: '(비사카 므느다팟 펭게말리안 우앙?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Di mana halte bus?', pronunciation: '(디 마나 할테 부스?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Bagaimana cara ke stasiun?', pronunciation: '(바가이나나 차라 케 스타시운?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Apakah jauh?', pronunciation: '(아파카 자우흐?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Bisakah saya mendapat peta?', pronunciation: '(비사카 사야 므느다팟 페타?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Di mana stasiun kereta bawah tanah terdekat?', pronunciation: '(디 마나 스타시운 케레타 바와흐 타나흐 터르데캇?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: '2 dewasa dan 1 anak', pronunciation: '(2 드와사 단 1 아낙)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'Jam berapa buka?', pronunciation: '(잠 베라파 부카?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'Jam berapa tutup?', pronunciation: '(잠 베라파 투투프?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Bolehkah foto di sini?', pronunciation: '(볼레카 포토 디 시니?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Saya tidak enak badan', pronunciation: '(사야 티닥 에낙 바단)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Saya perlu dokter', pronunciation: '(사야 페를루 독테르)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Saya sakit kepala', pronunciation: '(사야 사킷 케팔라)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Tolong panggil polisi', pronunciation: '(톨롱 팡길 폴리시)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Sepertinya saya kehilangan paspor', pronunciation: '(세페르티냐 사야 케힐랑안 파스포르)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Sepertinya saya kehilangan dompet', pronunciation: '(세페르티냐 사야 케힐랑안 돔펫)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Sepertinya saya kehilangan ponsel', pronunciation: '(세페르티냐 사야 케힐랑안 폰셀)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Di mana kantor barang hilang?', pronunciation: '(디 마나 칸토르 바랑 힐랑?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Bisakah menuliskannya untuk saya?', pronunciation: '(비사카 므눌리스칸냐 운투크 사야?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Tolong bicara lebih lambat', pronunciation: '(톨롱 비차라 레비히 람바트)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Di mana apotek terdekat?', pronunciation: '(디 마나 아포텍 터르데캇?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Saya perlu obat sakit kepala', pronunciation: '(사야 페를루 오밧 사킷 케팔라)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Saya perlu obat sakit perut', pronunciation: '(사야 페를루 오밧 사킷 페루트)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Saya perlu obat pilek', pronunciation: '(사야 페를루 오밧 필렉)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Ada plester?', pronunciation: '(아다 플레스테르?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Di mana kamar saya?', pronunciation: '디 마나 카마르 사야?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Bagasi saya belum sampai', pronunciation: '바가시 사야 벨룸 삼파이', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Di mana latihan keselamatan?', pronunciation: '디 마나 라티한 케셀라마탄?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'Pukul berapa saya harus kembali ke kapal?', pronunciation: '푸쿨 베라파 사야 하루스 켐발리 케 카팔?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Sekarang jam kapal berapa?', pronunciation: '세카랑 잠 카팔 베라파?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Di mana ruang medis?', pronunciation: '디 마나 루앙 메디스?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Bisakah saya mendapat obat mabuk laut?', pronunciation: '비사카 사야 므느다팟 오밧 마부크 라웃?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'Saya kehilangan kartu kamar (kunci kamar)', pronunciation: '사야 케힐랑안 카르투 카마르 (쿤치 카마르)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Di mana restoran prasmanan?', pronunciation: '디 마나 레스토란 프라스마난?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Jam makan malam dan meja saya berapa?', pronunciation: '잠 마칸 말람 단 메자 사야 베라파?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Bisakah saya memesan layanan kamar?', pronunciation: '비사카 사야 메메산 라야난 카마르?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Saya ingin memesan restoran (Italia)', pronunciation: '사야 잉긴 메메산 레스토란 (이탈리아)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Di mana saya bisa mendapatkan jadwal harian?', pronunciation: '디 마나 사야 비사 므느다팟 잣왈 하리안?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Saya ingin memesan tur pantai ini', pronunciation: '사야 잉긴 메메산 투르 판타이 이니', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Di mana titik pertemuan untuk tur?', pronunciation: '디 마나 티틱 페르테무안 운투크 투르?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Bagaimana cara menghubungkan Wi-Fi?', pronunciation: '바가이나나 차라 므느허붕칸 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Apakah ini termasuk (gratis)?', pronunciation: '아파카 이니 터르마수크 (그라티스)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Tolong bersihkan kamar saya', pronunciation: '톨롱 베르시칸 카마르 사야', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'Brankas di kamar saya tidak berfungsi', pronunciation: '브란카스 디 카마르 사야 티닥 베르푱시', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Di mana lift terdekat?', pronunciation: '디 마나 리프 테르데캇?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Apakah Anda berbicara bahasa Inggris?', pronunciation: '(아파카 안다 베르비차라 바하사 잉그리스?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Di mana kamar mandi?', pronunciation: '(디 마나 카마르 만디?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Bolehkah saya mencobanya?', pronunciation: '(볼레카 사야 믄초반야?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Terima kasih', pronunciation: '(터리마 카시흐)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Tolong bicara lebih lambat', pronunciation: '(톨롱 비차라 레비히 람바트)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
