import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Dov\'è il banco di accettazione?', pronunciation: '(도베 일 반코 디 아체타치오네?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Posso avere un posto vicino al finestrino?', pronunciation: '(포소 아베레 운 포스토 비치노 알 피네스트리노?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Quanto costa il bagaglio aggiuntivo?', pronunciation: '(콴토 코스타 일 바갈리오 아준티보?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Ho una prenotazione a nome (nome)', pronunciation: '(오 우나 프레노타치오네 아 노메 (이름))', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Potrei avere un altro asciugamano?', pronunciation: '(포트레이 아베레 운 알트로 아슈가마노?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'A che ora viene servita la colazione?', pronunciation: '(아 케 오라 비에네 세르비타 라 콜라치오네?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Potreste custodire il mio bagaglio dopo il check-out?', pronunciation: '(포트레스테 쿠스토디레 일 미오 바갈리오 도포 일 체크아웃?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Sono arrivato prima dell\'orario di check-in, potreste custodire il mio bagaglio?', pronunciation: '(소노 아리바토 프리마 델로라리오 디 체크인, 포트레스테 쿠스토디레 일 미오 바갈리오?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Il Wi-Fi non funziona nella mia stanza', pronunciation: '(일 와이파이 논 푼치오나 넬라 미아 스탄차)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'L\'aria condizionata non funziona', pronunciation: '(라리아 콘디치오나타 논 푼치오나)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'L\'acqua calda non funziona', pronunciation: '(라쿠아 칼다 논 푼치오나)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'È possibile fare un check-out tardivo?', pronunciation: '(에 포시빌레 파레 운 체크아웃 타르디보?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Potreste chiamarmi un taxi?', pronunciation: '(포트레스테 키아마르미 운 택시?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Posso vedere il menu?', pronunciation: '(포소 베데레 일 메뉴?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Vorrei ordinare (nome del piatto)', pronunciation: '(보레이 오르디나레 (요리 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Acqua, per favore', pronunciation: '(아쿠아, 페르 파보레)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Posso avere il conto?', pronunciation: '(포소 아베레 일 콘토?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Qual è il piatto più popolare qui?', pronunciation: '(콸 에 일 피아토 피우 포폴라레 퀴?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Cosa mi consigliate?', pronunciation: '(코사 미 콘실리아테?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Sono allergico alle noci', pronunciation: '(소노 알레르지코 알레 노치)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Contiene arachidi?', pronunciation: '(콘티에네 아라키디?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Posso portarlo via?', pronunciation: '(포소 포르탈로 비아?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Possiamo avere conti separati?', pronunciation: '(포시아모 아베레 콘티 세파라티?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Quanto costa questo?', pronunciation: '(콴토 코스타 퀘스토?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Ce l\'ha in un\'altra taglia?', pronunciation: '(체 라 인 우날트라 탈리아?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Posso pagare con carta?', pronunciation: '(포소 파가레 콘 카르타?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Posso avere un rimborso?', pronunciation: '(포소 아베레 운 림보르소?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Scusi, dov\'è la fermata dell\'autobus?', pronunciation: '(스쿠시, 도베 라 페르마타 델라우토부스?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Come posso arrivare alla stazione?', pronunciation: '(코메 포소 아리바레 알라 스타치오네?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'È lontano?', pronunciation: '(에 론타노?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Posso avere una mappa?', pronunciation: '(포소 아베레 우나 마파?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Dov\'è la stazione della metropolitana più vicina?', pronunciation: '(도베 라 스타치오네 델라 메트로폴리타나 피우 비치나?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Due adulti e un bambino, per favore', pronunciation: '(두에 아둘티 에 운 밤비노, 페르 파보레)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'A che ora apre?', pronunciation: '(아 케 오라 아프레?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'A che ora chiude?', pronunciation: '(아 케 오라 키우데?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Posso fare una foto qui?', pronunciation: '(포소 파레 우나 포토 퀴?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Non mi sento bene', pronunciation: '(논 미 센토 베네)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Ho bisogno di un dottore', pronunciation: '(오 비소뇨 디 운 도토레)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Ho mal di testa', pronunciation: '(오 말 디 테스타)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Chiami la polizia', pronunciation: '(키아미 라 폴리치아)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Sembra che abbia perso il mio passaporto', pronunciation: '(셈브라 케 아비아 페르소 일 미오 파사포르토)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Sembra che abbia perso il mio portafoglio', pronunciation: '(셈브라 케 아비아 페르소 일 미오 포르타폴리오)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Sembra che abbia perso il mio telefono', pronunciation: '(셈브라 케 아비아 페르소 일 미오 텔레포노)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Dov\'è l\'ufficio oggetti smarriti?', pronunciation: '(도베 루피치오 오제티 스마리티?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Potreste scriverlo qui per favore?', pronunciation: '(포트레스테 스크리베를로 퀴 페르 파보레?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Per favore, parli più lentamente', pronunciation: '(페르 파보레, 파를리 피우 렌타멘테)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Dov\'è la farmacia più vicina?', pronunciation: '(도베 라 파르마치아 피우 비치나?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Ho bisogno di qualcosa per il mal di testa', pronunciation: '(오 비소뇨 디 콸코사 페르 일 말 디 테스타)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Ho bisogno di qualcosa per il mal di stomaco', pronunciation: '(오 비소뇨 디 콸코사 페르 일 말 디 스토마코)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Ho bisogno di qualcosa per il raffreddore', pronunciation: '(오 비소뇨 디 콸코사 페르 일 라프레도레)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Avete cerotti?', pronunciation: '(아베테 체로티?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Dov\'è la mia cabina?', pronunciation: '도베 라 미아 카비나?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Il mio bagaglio non è ancora arrivato', pronunciation: '일 미오 바갈리오 논 에 안코라 아리바토', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Dov\'è l\'esercitazione di sicurezza?', pronunciation: '도베 레세르치타치오네 디 시쿠레차?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'A che ora devo tornare sulla nave?', pronunciation: '아 케 오라 데보 토르나레 술라 나베?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Che ore sono (orario di bordo)?', pronunciation: '케 오레 소노 (오라리오 디 보르도)?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Dov\'è il centro medico?', pronunciation: '도베 일 첸트로 메디코?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Posso avere qualcosa per il mal di mare?', pronunciation: '포소 아베레 콸코사 페르 일 말 디 마레?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'Ho perso la mia carta della nave', pronunciation: '오 페르소 라 미아 카르타 델라 나베', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Dov\'è il ristorante a buffet?', pronunciation: '도베 일 리스토란테 아 부페?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Qual è il mio turno e tavolo per la cena?', pronunciation: '콸 에 일 미오 투르노 에 타볼로 페르 라 체나?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Posso ordinare il servizio in camera?', pronunciation: '포소 오르디나레 일 세르비치오 인 카메라?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Vorrei prenotare al ristorante (italiano)', pronunciation: '보레이 프레노타레 알 리스토란테 (이탈리아노)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Dove posso prendere il programma del giorno?', pronunciation: '도베 포소 프렌데레 일 프로그람마 델 조르노?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Vorrei prenotare questa escursione a terra', pronunciation: '보레이 프레노타레 퀘스타 에스쿠르시오네 아 테라', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Dov\'è il punto d\'incontro per il tour?', pronunciation: '도베 일푼토 딘콘트로 페르 일 투어?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Come mi connetto al Wi-Fi?', pronunciation: '코메 미 콘네토 알 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Questo è incluso (gratuito)?', pronunciation: '퀘스토 에 인클루소 (그라투이토)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Per favore, può rifare la mia camera?', pronunciation: '페르 파보레, 푸오 리파레 라 미아 카메라?', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'La cassaforte nella mia camera non funziona', pronunciation: '라 카사포르테 넬라 미아 카메라 논 푼치오나', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Dov\'è l\'ascensore più vicino?', pronunciation: '도베 라셴소레 피우 비치노?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Parli inglese?', pronunciation: '(파를리 인글레세?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Dov\'è il bagno?', pronunciation: '(도베 일 바뇨?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Posso provarlo?', pronunciation: '(포소 프로바로?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Grazie', pronunciation: '(그라치에)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Per favore, parli lentamente', pronunciation: '(페르 파보레, 파를리 렌타멘테)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
