import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'チェックインカウンターはどこですか？', pronunciation: '(첵쿠인 카운타-와 도코데스카?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: '窓側の席をお願いします', pronunciation: '(마도가와노 세키오 오네가이시마스)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: '追加手荷物の料金はいくらですか？', pronunciation: '(츠이카 테니모츠노 료-킨와 이쿠라데스카?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: '(名前)で予約しました', pronunciation: '((나마에)데 요야쿠시마시타)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'タオルをもう1枚いただけますか？', pronunciation: '(타오루오 모- 이치마이 이타다케마스카?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: '朝食は何時に提供されますか？', pronunciation: '(쵸-쇼쿠와 난지니 테이쿄-사레마스카?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'チェックアウト後に荷物を預かってもらえますか？', pronunciation: '(첵쿠아우토 고니 니모츠오 아즈캇테 모라에마스카?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'チェックイン時間より早く到着しましたが、荷物を預かってもらえますか？', pronunciation: '(첵쿠인 지칸요리 하야쿠 토-챠쿠시마시타가, 니모츠오 아즈캇테 모라에마스카?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: '私の部屋でWi-Fiが機能していません', pronunciation: '(와타시노 헤야데 와이파이가 키노-시테 이마셍)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'エアコンが機能していません', pronunciation: '(에아콘가 키노-시테 이마셍)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'お湯が出ません', pronunciation: '(오유가 데마셍)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'チェックアウトを少し遅らせることはできますか？', pronunciation: '(첵쿠아우토오 스코시 오쿠라세루 코토와 데키마스카?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'タクシーを1台呼んでいただけますか？', pronunciation: '(타쿠시-오 이치다이 욘데 이타다케마스카?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'メニューを見せていただけますか？', pronunciation: '(메뉴-오 미세테 이타다케마스카?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'これを注文します', pronunciation: '(코레오 츄-몬시마스)', emoji: '🍴' },
      { ko: '물 좀 주세요', target: '水をお願いします', pronunciation: '(미즈오 오네가이시마스)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'お会計をお願いします', pronunciation: '(오카이케-오 오네가이시마스)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'ここで一番人気のメニューは何ですか？', pronunciation: '(코코데 이치반 닌키노 메뉴-와 난데스카?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: '何をお勧めしますか？', pronunciation: '(나니오 오스스메시마스카?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: '私はナッツアレルギーがあります', pronunciation: '(와타시와 낫츠 아레루기-가 아리마스)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'これにはピーナッツが含まれていますか？', pronunciation: '(코레니와 피-낫츠가 후쿠마레테 이마스카?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'これを持ち帰りにできますか？', pronunciation: '(코레오 모치카에리니 데키마스카?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'お会計を別々にしていただけますか？', pronunciation: '(오카이케-오 베츠베츠니 이타다케마스카?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'これはいくらですか？', pronunciation: '(코레와 이쿠라데스카?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'これは他のサイズがありますか？', pronunciation: '(코레와 호카노 사이즈가 아리마스카?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'カードで支払えますか？', pronunciation: '(카-도데 시하라에마스카?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: '返金できますか？', pronunciation: '(헨킨 데키마스카?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'すみません、バス停はどこですか？', pronunciation: '(스미마셍, 바스테-와 도코데스카?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: '駅にはどうやって行けばいいですか？', pronunciation: '(에키니와 도-얏테 이케바 이이데스카?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: '遠いですか？', pronunciation: '(토오이데스카?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: '地図をいただけますか？', pronunciation: '(치즈오 이타다케마스카?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: '最も近い地下鉄駅はどこですか？', pronunciation: '(못토모 치카이 치카테츠 에키와 도코데스카?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: '大人2名、子供1名お願いします', pronunciation: '(오토나 니메이, 코도모 이치메이 오네가이시마스)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: '何時に開きますか？', pronunciation: '(난지니 아키마스카?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: '何時に閉まりますか？', pronunciation: '(난지니 시마리마스카?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'ここで写真を撮ってもいいですか？', pronunciation: '(코코데 샤신오 톳테모 이이데스카?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: '気分が悪いです', pronunciation: '(키분가 와루이데스)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: '医者が必要です', pronunciation: '(이샤가 히츠요-데스)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: '頭痛があります', pronunciation: '(즈츠-가 아리마스)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: '警察を呼んでください', pronunciation: '(케-사츠오 욘데 쿠다사이)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'パスポートを失くしたようです', pronunciation: '(파스포-토오 나쿠시타 요-데스)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: '財布を失くしたようです', pronunciation: '(사이후오 나쿠시타 요-데스)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: '携帯電話を失くしたようです', pronunciation: '(케-타이뎅와오 나쿠시타 요-데스)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: '遺失物取扱所はどこですか？', pronunciation: '(이시츠부츠 토리아츠카이조와 도코데스카?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'ここに書いていただけますか？', pronunciation: '(코코니 카이테 이타다케마스카?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'もう少しゆっくり話していただけますか？', pronunciation: '(모- 스코시 윳쿠리 하나시테 이타다케마스카?)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: '最も近い薬局はどこですか？', pronunciation: '(못토모 치카이 약쿄쿠와 도코데스카?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: '頭痛薬が必要です', pronunciation: '(즈츠-야쿠가 히츠요-데스)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: '腹痛薬が必要です', pronunciation: '(후쿠츠-야쿠가 히츠요-데스)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: '風邪薬が必要です', pronunciation: '(카제구스리가 히츠요-데스)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: '絆創膏はありますか？', pronunciation: '(반소-코-와 아리마스카?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: '私の客室はどこですか？', pronunciation: '와타시노 캬쿠시츠와 도코데스카?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: '私の荷物がまだ届いていません', pronunciation: '와타시노 니모츠가 마다 토도이테 이마셍', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: '避難訓練はどこですか？', pronunciation: '히난 쿤렌와 도코데스카?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: '何時までに船に戻る必要がありますか？', pronunciation: '난지마데니 후네니 모도루 히츠요-가 아리마스카?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: '今の船内時間は何時ですか？', pronunciation: '이마노 센나이 지칸와 난지데스카?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: '医務室はどこですか？', pronunciation: '이무시츠와 도코데스카?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: '船酔いの薬をもらえますか？', pronunciation: '후나요이노 쿠스리오 모라에마스카?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'ルームキー(船内カード)を失くしました', pronunciation: '루-무키- (센나이 카-도) 오 나쿠시마시타', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'ビュッフェレストランはどこですか？', pronunciation: '뷧페 레스토랑와 도코데스카?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: '私の夕食時間とテーブルはどこですか？', pronunciation: '와타시노 유-쇼쿠 지칸토 테-부루와 도코데스카?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'ルームサービスを注文できますか？', pronunciation: '루-무 사-비스오 츄-몬 데키마스카?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: '(イタリアン)レストランを予約したいです', pronunciation: '(이타리안) 레스토랑오 요야쿠시타이데스', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: '本日のスケジュールはどこでもらえますか？', pronunciation: '혼지츠노 스케쥬-루와 도코데 모라에마스카?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'この寄港地観光を予約したいです', pronunciation: '코노 키코-치 칸코-오 요야쿠시타이데스', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'ツアーの集合場所はどこですか？', pronunciation: '츠아-노 슈-고- 바쇼와 도코데스카?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Wi-Fiはどうやって接続しますか？', pronunciation: '와이파이와 도-얏테 세츠조쿠시마스카?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'これは無料ですか？ (含まれていますか？)', pronunciation: '코레와 무료-데스카? (후쿠마레테 이마스카?)', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: '部屋の掃除をお願いします', pronunciation: '헤야노 소-지오 오네가이시마스', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: '部屋の金庫が動きません', pronunciation: '헤야노 킨코가 우고키마셍', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: '一番近いエレベーターはどこですか？', pronunciation: '이치반 치카이 에레베-타-와 도코데스카?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: '英語を話せますか？', pronunciation: '(에-고오 하나세마스카?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'トイレはどこですか？', pronunciation: '(토이레와 도코데스카?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'これを試着できますか？', pronunciation: '(코레오 시챠쿠 데키마스카?)', emoji: '👕' },
      { ko: '감사합니다', target: 'ありがとうございます', pronunciation: '(아리가토- 고자이마스)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'ゆっくり話してください', pronunciation: '(윳쿠리 하나시테 쿠다사이)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
