import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Di mana kaunter daftar masuk?', pronunciation: '(디 마나 카운터 다프타르 마수크?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Tolong beri saya kerusi dekat tingkap', pronunciation: '(톨롱 베리 사야 쿠루시 데캇 팅캡)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Berapa kos bagasi tambahan?', pronunciation: '(베라파 코스 바가시 탐바한?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Saya sudah menempah atas nama (nama)', pronunciation: '((이름) 나마)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Bolehkah saya dapat tuala tambahan?', pronunciation: '(볼레카 사야 다팟 투알라 탐바한?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'Jam berapa sarapan disediakan?', pronunciation: '(잠 베라파 사라판 디세디아칸?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Bolehkah simpan beg saya selepas saya daftar keluar?', pronunciation: '(볼레카 심판 베그 사야 셀레파스 사야 다프타르 쿠루아르?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Saya sampai awal dari masa daftar masuk, bolehkah simpan beg?', pronunciation: '(사야 삼파이 아왈 다리 마사 다프타르 마수크, 볼레카 심판 베그?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Wi-Fi di bilik saya tidak berfungsi', pronunciation: '(와이파이 디 빌릭 사야 티닥 베르푱시)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'Penyaman udara tidak berfungsi', pronunciation: '(페니아만 우다라 티닥 베르푱시)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'Air panas tidak keluar', pronunciation: '(아이르 파나스 티닥 케루아르)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Bolehkah daftar keluar lewat?', pronunciation: '(볼레카 다프타르 쿠루아르 레왓?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Bolehkah panggil teksi untuk saya?', pronunciation: '(볼레카 팡길 텍시 운투크 사야?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Bolehkah saya lihat menu?', pronunciation: '(볼레카 사야 리헷 메뉴?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Saya ingin menempah (nama makanan)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Tolong air', pronunciation: '(톨롱 아이르)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Bolehkah saya dapat bil?', pronunciation: '(볼레카 사야 다팟 빌?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Apa hidangan paling popular di sini?', pronunciation: '(아파 히당안 팔링 포풀라르 디 시니?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Apa yang anda cadangkan?', pronunciation: '(아파 양 안다 차당칸?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Saya alergi terhadap kacang', pronunciation: '(사야 알레르기 터르하답 카창)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Adakah ini mengandungi kacang tanah?', pronunciation: '(아다카 이니 망구응이 카창 타나흐?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Bolehkah bungkus bawa balik?', pronunciation: '(볼레카 붕쿠스 바와 발릭?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Bolehkah bil dipisahkan?', pronunciation: '(볼레카 빌 디피사칸?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Berapa harga ini?', pronunciation: '(베라파 하르가 이니?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Ada saiz lain?', pronunciation: '(아다 사이즈 라인?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Bolehkah bayar dengan kad?', pronunciation: '(볼레카 바야르 드응안 카드?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Bolehkah mendapat bayaran balik?', pronunciation: '(볼레카 므느다팟 바야란 발릭?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Di mana perhentian bas?', pronunciation: '(디 마나 페르헨티안 바스?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Bagaimana cara ke stesen?', pronunciation: '(바가이나나 차라 케 스테센?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Adakah jauh?', pronunciation: '(아다카 자우흐?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Bolehkah saya dapat peta?', pronunciation: '(볼레카 사야 다팟 페타?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Di mana stesen kereta api bawah tanah terdekat?', pronunciation: '(디 마나 스테센 케레타 아피 바와흐 타나흐 터르데캇?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: '2 dewasa dan 1 kanak-kanak', pronunciation: '(2 드와사 단 1 카낙-카낙)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'Jam berapa buka?', pronunciation: '(잠 베라파 부카?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'Jam berapa tutup?', pronunciation: '(잠 베라파 투투프?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Bolehkah ambil foto di sini?', pronunciation: '(볼레카 암빌 포토 디 시니?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Saya tidak sihat', pronunciation: '(사야 티닥 시헷)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Saya perlukan doktor', pronunciation: '(사야 페를루칸 독토르)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Saya sakit kepala', pronunciation: '(사야 사킷 케팔라)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Tolong panggil polis', pronunciation: '(톨롱 팡길 폴리스)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Saya nampaknya kehilangan pasport', pronunciation: '(사야 남팡카 케힐랑안 파스포르트)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Saya nampaknya kehilangan dompet', pronunciation: '(사야 남팡카 케힐랑안 돔펫)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Saya nampaknya kehilangan telefon bimbit', pronunciation: '(사야 남팡카 케힐랑안 텔레폰 빔빗)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Di mana pejabat barang hilang?', pronunciation: '(디 마나 페자밧 바랑 힐랑?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Bolehkah tuliskan untuk saya?', pronunciation: '(볼레카 툴리스칸 운투크 사야?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Tolong cakap lebih perlahan', pronunciation: '(톨롱 차캅 레비히 페를라한)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Di mana farmasi terdekat?', pronunciation: '(디 마나 파르마시 터르데캇?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Saya perlukan ubat sakit kepala', pronunciation: '(사야 페를루칸 우밧 사킷 케팔라)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Saya perlukan ubat sakit perut', pronunciation: '(사야 페를루칸 우밧 사킷 페루트)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Saya perlukan ubat selsema', pronunciation: '(사야 페를루칸 우밧 셀세마)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Ada plaster?', pronunciation: '(아다 플라스테르?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Di mana bilik saya?', pronunciation: '디 마나 빌릭 사야?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Bagasi saya belum sampai', pronunciation: '바가시 사야 벨룸 삼파이', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Di mana latihan keselamatan?', pronunciation: '디 마나 라티한 케셀라마탄?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'Pukul berapa saya perlu kembali ke kapal?', pronunciation: '푸쿨 베라파 사야 페를루 켐발리 케 카팔?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Sekarang masa kapal pukul berapa?', pronunciation: '세카랑 마사 카팔 푸쿨 베라파?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Di mana bilik perubatan?', pronunciation: '디 마나 빌릭 페루바탄?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Bolehkah saya dapat ubat mabuk laut?', pronunciation: '볼레카 사야 다팟 우밧 마부크 라웃?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'Saya kehilangan kad bilik (kunci bilik)', pronunciation: '사야 케힐랑안 카드 빌릭 (쿤치 빌릭)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Di mana restoran bufet?', pronunciation: '디 마나 레스토란 부펫?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Masa makan malam dan meja saya berapa?', pronunciation: '마사 마칸 말람 단 메자 사야 베라파?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Bolehkah saya memesan khidmat bilik?', pronunciation: '볼레카 사야 메메산 히드맛 빌릭?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Saya ingin menempah restoran (Itali)', pronunciation: '사야 잉긴 메넘파 레스토란 (이탈리)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Di mana saya boleh dapat jadual harian?', pronunciation: '디 마나 사야 볼레 다팟 자두알 하리안?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Saya ingin menempah lawatan pantai ini', pronunciation: '사야 잉긴 메넘파 라와탄 판타이 이니', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Di mana titik pertemuan untuk lawatan?', pronunciation: '디 마나 티틱 페르테무안 운투크 라와탄?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Bagaimana cara sambungkan Wi-Fi?', pronunciation: '바가이나나 차라 삼붕칸 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Adakah ini termasuk (percuma)?', pronunciation: '아다카 이니 터르마수크 (페르추마)?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Tolong bersihkan bilik saya', pronunciation: '톨롱 베르시칸 빌릭 사야', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'Peti besi di bilik saya tidak berfungsi', pronunciation: '페티 베시 디 빌릭 사야 티닥 베르푱시', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Di mana lif terdekat?', pronunciation: '디 마나 리프 테르데캇?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Adakah anda bercakap bahasa Inggeris?', pronunciation: '(아다카 안다 베르차캅 바하사 잉그리스?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Di mana tandas?', pronunciation: '(디 마나 탄다스?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Bolehkah saya cuba?', pronunciation: '(볼레카 사야 추바?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Terima kasih', pronunciation: '(터리마 카시흐)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Tolong cakap lebih perlahan', pronunciation: '(톨롱 차캅 레비히 페를라한)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
