import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'เคาน์เตอร์เช็คอินอยู่ที่ไหน?', pronunciation: '(케운터-첵인 유 티 나이?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'ขอที่นั่งริมหน้าต่างได้ไหม?', pronunciation: '(코 티 낭 림 나 탕 다이 마이?)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'ค่าธรรมเนียมกระเป๋าเพิ่มเติมเท่าไหร่?', pronunciation: '(카 탐니암 끄라빠오 펨 텀 타오라이?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'ฉันจองในชื่อ(ชื่อ)', pronunciation: '((이름) 차이)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'ขอผ้าเช็ดตัวเพิ่มได้ไหม?', pronunciation: '(코 파 첫 타우 펨 다이 마이?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'อาหารเช้าเสิร์ฟเวลาเท่าไหร่?', pronunciation: '(아한 차오 셉 웰라 타오라이?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'เช็คเอาท์แล้วช่วยเก็บกระเป๋าให้ได้ไหม?', pronunciation: '(첵아웃 레우 추아이 켑 끄라빠오 하이 다이 마이?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'มาถึงก่อนเวลาเช็คอินช่วยเก็บกระเป๋าให้ได้ไหม?', pronunciation: '(마 턍 콘 웰라 첵인 추아이 켑 끄라빠오 하이 다이 마이?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Wi-Fi ในห้องของฉันไม่ทำงาน', pronunciation: '(와이파이 나이 홍 콩 찬 마이 탐응안)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'เครื่องปรับอากาศไม่ทำงาน', pronunciation: '(끄렁 프랍 아갓 마이 탐응안)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'น้ำอุ่นไม่ไหล', pronunciation: '(남 운 마이 라이)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'ขอเช็คเอาท์ช้าได้ไหม?', pronunciation: '(코 첵아웃 차 다이 마이?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'ช่วยเรียกแท็กซี่ให้ได้ไหม?', pronunciation: '(추아이 리악 택시 하이 다이 마이?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'ขอดูเมนูได้ไหม?', pronunciation: '(코 두 메누 다이 마이?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'ฉันต้องการสั่ง(ชื่ออาหาร)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'ขอน้ำได้ไหม?', pronunciation: '(코 남 다이 마이?)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'เช็คบิลได้ไหม?', pronunciation: '(첵 빌 다이 마이?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'เมนูที่นิยมที่นี่คืออะไร?', pronunciation: '(메누 티 니욤 티 니 크 아라이?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'คุณแนะนำอะไร?', pronunciation: '(쿤 너남 아라이?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'ฉันแพ้ถั่ว', pronunciation: '(찬 패 투아)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'มีถั่วลิสงไหม?', pronunciation: '(미 투아 리송 마이?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'ห่อกลับบ้านได้ไหม?', pronunciation: '(호 끌랍 반 다이 마이?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'แยกบิลได้ไหม?', pronunciation: '(예억 빌 다이 마이?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'นี่ราคาเท่าไหร่?', pronunciation: '(니 라카 타오라이?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'มีไซส์อื่นไหม?', pronunciation: '(미 사이 어운 마이?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'จ่ายด้วยบัตรได้ไหม?', pronunciation: '(자이 두아이 밧 다이 마이?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'ขอคืนเงินได้ไหม?', pronunciation: '(코 쿤 응안 다이 마이?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'ป้ายรถเมล์อยู่ที่ไหน?', pronunciation: '(파이 롯 멜 유 티 나이?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'ไปสถานีได้อย่างไร?', pronunciation: '(파이 사타니 다이 양라이?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'ไกลไหม?', pronunciation: '(클라이 마이?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'ขอแผนที่ได้ไหม?', pronunciation: '(코 팬 티 다이 마이?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'สถานีรถไฟใต้ดินที่ใกล้ที่สุดอยู่ที่ไหน?', pronunciation: '(사타니 롯 파이 타이 딘 티 클라이 티 수트 유 티 나이?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'ผู้ใหญ่ 2 คน เด็ก 1 คน', pronunciation: '(푸 야이 2 콘 덱 1 콘)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'เปิดกี่โมง?', pronunciation: '(뻬드 기 몽?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'ปิดกี่โมง?', pronunciation: '(핏 기 몽?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'ถ่ายรูปที่นี่ได้ไหม?', pronunciation: '(타이 룹 티 니 다이 마이?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'ฉันรู้สึกไม่ดี', pronunciation: '(찬 루석 마이 디)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'ฉันต้องการหมอ', pronunciation: '(찬 통간 모)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'ฉันปวดหัว', pronunciation: '(찬 푸앗 후아)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'ช่วยเรียกตำรวจได้ไหม?', pronunciation: '(추아이 리악 탐루악 다이 마이?)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'ฉันน่าจะทำพาสปอร์ตหาย', pronunciation: '(찬 나 자 탐 파스포트 하이)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'ฉันน่าจะทำกระเป๋าตังค์หาย', pronunciation: '(찬 나 자 탐 끄라빠오 탕 하이)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'ฉันน่าจะทำโทรศัพท์หาย', pronunciation: '(찬 나 자 탐 토랏솝 하이)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'ศูนย์พบของหายอยู่ที่ไหน?', pronunciation: '(수니 폭 콩 하이 유 티 나이?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'ช่วยเขียนให้ได้ไหม?', pronunciation: '(추아이 키엔 하이 다이 마이?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'พูดช้ากว่านี้ได้ไหม?', pronunciation: '(푸트 차 간 나이 다이 마이?)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'ร้านขายยาที่ใกล้ที่สุดอยู่ที่ไหน?', pronunciation: '(란 카이 야 티 클라이 티 수트 유 티 나이?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'ฉันต้องการยาปวดหัว', pronunciation: '(찬 통간 야 푸앗 후아)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'ฉันต้องการยาปวดท้อง', pronunciation: '(찬 통간 야 푸앗 통)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'ฉันต้องการยาแก้หวัด', pronunciation: '(찬 통간 야 개 왓)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'มีพลาสเตอร์ไหม?', pronunciation: '(미 플라스터 마이?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'ห้องของฉันอยู่ที่ไหน?', pronunciation: '홍 콩 찬 유 티 나이?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'กระเป๋าของฉันยังไม่มาถึง', pronunciation: '끄라빠오 콩 찬 양 마이 마 틍', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'ฝึกซ้อมด้านความปลอดภัยอยู่ที่ไหน?', pronunciation: '푹 쌈 단 콴 플로이 사이 유 티 나이?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'ฉันต้องกลับมาที่เรือภายในเวลาเท่าไหร่?', pronunciation: '찬 통 끌랍 마 티 뤼어 파이 나이 웰라 타오라이?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'ตอนนี้เวลาบนเรือเป็นเท่าไหร่?', pronunciation: '톤 니 웰라 본 뤼어 펜 타오라이?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'ห้องพยาบาลอยู่ที่ไหน?', pronunciation: '홍 빠야반 유 티 나이?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'ขอยารักษาเมาคลื่นได้ไหม?', pronunciation: '코 야 락사 마오 클륀 다이 마이?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'ฉันทำบัตรห้อง(กุญแจห้อง)หาย', pronunciation: '찬 탐 밧 홍 (쿤짠 홍) 하이', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'ร้านบุฟเฟต์อยู่ที่ไหน?', pronunciation: '란 부페 유 티 나이?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'เวลาอาหารเย็นและโต๊ะของฉันคืออะไร?', pronunciation: '웰라 아한 옌 렉 토 찬 콩 찬 크 아라이?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'สามารถสั่งบริการในห้องได้ไหม?', pronunciation: '사맏 상 보리간 나이 홍 다이 마이?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'ฉันต้องการจองร้านอาหาร(อิตาเลียน)', pronunciation: '찬 통간 종 란 아한 (이타리안)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'ฉันสามารถรับตารางประจำวันได้ที่ไหน?', pronunciation: '찬 사맏 랍 타이랑 짬완 다이 티 나이?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'ฉันต้องการจองทัวร์บนฝั่งนี้', pronunciation: '찬 통간 종 투어 본 팡 니', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'จุดนัดพบสำหรับทัวร์อยู่ที่ไหน?', pronunciation: '줃 낟 폭 삼랍 투어 유 티 나이?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'ฉันจะเชื่อมต่อ Wi-Fi ได้อย่างไร?', pronunciation: '찬 자 츄암 토 와이파이 다이 양라이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'นี่รวมอยู่ในค่าใช้จ่ายแล้วหรือยัง?', pronunciation: '니 루암 유 나이 카 차이자이 레우 러 양?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'กรุณาทำความสะอาดห้องของฉัน', pronunciation: '끄루나 탐 콴 사앗 홍 콩 찬', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'ตู้นิรภัยในห้องของฉันไม่ทำงาน', pronunciation: '투 닐파이 나이 홍 콩 찬 마이 탐응안', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'ลิฟต์ที่ใกล้ที่สุดอยู่ที่ไหน?', pronunciation: '립 티 클라이 티 수트 유 티 나이?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'คุณพูดภาษาอังกฤษได้ไหม?', pronunciation: '(쿤 푸트 앙크리사다이 마이?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'ห้องน้ำอยู่ที่ไหน?', pronunciation: '(홍 남 유 티 나이?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'ลองใส่ได้ไหม?', pronunciation: '(롱 사이 다이 마이?)', emoji: '👕' },
      { ko: '감사합니다', target: 'ขอบคุณ', pronunciation: '(콥 쿤)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'พูดช้าๆได้ไหม?', pronunciation: '(푸트 차 차 다이 마이?)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
