import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: 'Quầy làm thủ tục ở đâu?', pronunciation: '(쿠아이 람 투 튝 어 더우?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: 'Xin cho tôi ghế ngồi cạnh cửa sổ', pronunciation: '(신 초 토이 게 응오이 캉 쿠아 쇼)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: 'Phí hành lý ký gửi thêm là bao nhiêu?', pronunciation: '(피 항 리 키 구이 템 라 바오 느우?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: 'Tôi đã đặt phòng dưới tên (tên)', pronunciation: '((이름) 턴)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: 'Có thể cho tôi thêm một khăn tắm không?', pronunciation: '(코 테 초 토이 템 목 칸 담 콩?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: 'Bữa sáng được phục vụ lúc mấy giờ?', pronunciation: '(부아 상 독 푹 부 룩 매이 저?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: 'Có thể giữ hành lý của tôi sau khi tôi trả phòng không?', pronunciation: '(코 테 주 항 리 꾸아 토이 사우 키 토이 트라 퐁 콩?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: 'Tôi đến sớm hơn giờ nhận phòng, có thể giữ hành lý không?', pronunciation: '(토이 덴 솜 혼 저 녠 퐁, 코 테 주 항 리 콩?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: 'Wi-Fi trong phòng tôi không hoạt động', pronunciation: '(와이파이 쫑 퐁 토이 콩 호앗 동)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: 'Điều hòa không hoạt động', pronunciation: '(디우 호아 콩 호앗 동)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: 'Nước nóng không chảy', pronunciation: '(느억 농 콩 차이)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: 'Có thể trả phòng muộn được không?', pronunciation: '(코 테 트라 퐁 무언 독 콩?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: 'Có thể gọi taxi cho tôi không?', pronunciation: '(코 테 고이 택시 초 토이 콩?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: 'Cho tôi xem thực đơn được không?', pronunciation: '(초 토이 셈 툭 돈 독 콩?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: 'Tôi muốn gọi (tên món ăn)', pronunciation: '((음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: 'Xin cho nước', pronunciation: '(신 초 느억)', emoji: '💧' },
      { ko: '계산서 주세요', target: 'Cho tôi hóa đơn được không?', pronunciation: '(초 토이 호아 돈 독 콩?)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: 'Món nào phổ biến nhất ở đây?', pronunciation: '(몬 나오 포 비운 느엣 어 데이?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: 'Bạn gợi ý món gì?', pronunciation: '(반 고이 이 몬 지?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: 'Tôi bị dị ứng với các loại hạt', pronunciation: '(토이 비 지 응웅 브이 카크 로이 하트)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: 'Cái này có chứa đậu phộng không?', pronunciation: '(까이 나이 코 추아 다우 퐁 콩?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: 'Có thể đóng gói mang đi được không?', pronunciation: '(코 테 동 고이 망 디 독 콩?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: 'Có thể thanh toán riêng không?', pronunciation: '(코 테 탄 토안 리엥 콩?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: 'Cái này giá bao nhiêu?', pronunciation: '(까이 나이 자 바오 느우?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: 'Có size khác không?', pronunciation: '(코 사이즈 카크 콩?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: 'Có thể thanh toán bằng thẻ không?', pronunciation: '(코 테 탄 토안 빵 테 콩?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: 'Có thể hoàn tiền không?', pronunciation: '(코 테 호안 티엔 콩?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: 'Trạm xe buýt ở đâu?', pronunciation: '(짬 쎄 부이트 어 더우?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: 'Làm sao để đến ga?', pronunciation: '(람 사오 데 덴 가?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: 'Có xa không?', pronunciation: '(코 사 콩?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: 'Có thể cho tôi bản đồ không?', pronunciation: '(코 테 초 토이 반 도 콩?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: 'Ga tàu điện ngầm gần nhất ở đâu?', pronunciation: '(가 타우 디엔 응암 간 느엣 어 더우?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: 'Cho 2 người lớn và 1 trẻ em', pronunciation: '(초 2 느으이 런 바 1 짜이 엠)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: 'Mở cửa lúc mấy giờ?', pronunciation: '(모 쿠아 룩 매이 저?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: 'Đóng cửa lúc mấy giờ?', pronunciation: '(동 쿠아 룩 매이 저?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: 'Có thể chụp ảnh ở đây không?', pronunciation: '(코 테 추프 언 어 데이 콩?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: 'Tôi cảm thấy không khỏe', pronunciation: '(토이 캄 타이 콩 쿠에)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: 'Tôi cần bác sĩ', pronunciation: '(토이 깐 박 시)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: 'Tôi bị đau đầu', pronunciation: '(토이 비 다우 더우)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: 'Xin gọi cảnh sát', pronunciation: '(신 고이 까인 삿)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: 'Tôi có vẻ đã làm mất hộ chiếu', pronunciation: '(토이 코 베 다 람 맛 홉 치우)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: 'Tôi có vẻ đã làm mất ví', pronunciation: '(토이 코 베 다 람 맛 비)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: 'Tôi có vẻ đã làm mất điện thoại', pronunciation: '(토이 코 베 다 람 맛 디엔 토아이)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: 'Phòng tìm đồ thất lạc ở đâu?', pronunciation: '(퐁 땀 도 탓 랙 어 더우?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: 'Có thể viết ra cho tôi không?', pronunciation: '(코 테 비엣 라 초 토이 콩?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: 'Xin nói chậm hơn một chút', pronunciation: '(신 노이 참 혼 목 추트)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: 'Nhà thuốc gần nhất ở đâu?', pronunciation: '(냐 투옥 간 느엣 어 더우?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: 'Tôi cần thuốc đau đầu', pronunciation: '(토이 깐 투옥 다우 더우)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: 'Tôi cần thuốc đau bụng', pronunciation: '(토이 깐 투옥 다우 붕)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: 'Tôi cần thuốc cảm', pronunciation: '(토이 깐 투옥 캄)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: 'Có băng dán không?', pronunciation: '(코 방 단 콩?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: 'Phòng của tôi ở đâu?', pronunciation: '퐁 꾸아 토이 어 더우?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: 'Hành lý của tôi chưa đến', pronunciation: '항 리 꾸아 토이 추아 덴', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: 'Buổi diễn tập an toàn ở đâu?', pronunciation: '부이 디엔 탑 안 턴 어 더우?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: 'Tôi cần quay lại tàu lúc mấy giờ?', pronunciation: '토이 깐 꾸이 라이 타우 룩 매이 저?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: 'Bây giờ giờ trên tàu là mấy giờ?', pronunciation: '바이 저 저 트렌 타우 라 매이 저?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: 'Phòng y tế ở đâu?', pronunciation: '퐁 이 테 어 더우?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: 'Tôi có thể nhận thuốc say sóng không?', pronunciation: '토이 코 테 녠 투옥 사이 송 콩?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: 'Tôi đã làm mất thẻ phòng (chìa khóa phòng)', pronunciation: '토이 다 람 맛 테 퐁 (치아 쿠아 퐁)', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: 'Nhà hàng buffet ở đâu?', pronunciation: '냐 항 부페이 어 더우?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: 'Giờ ăn tối và bàn của tôi là gì?', pronunciation: '저 안 또이 바 반 꾸아 토이 라 지?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: 'Tôi có thể gọi dịch vụ phòng không?', pronunciation: '토이 코 테 고이 지익 부 퐁 콩?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: 'Tôi muốn đặt bàn tại nhà hàng (Ý)', pronunciation: '토이 무온 닷 반 다이 냐 항 (이)', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: 'Tôi có thể nhận lịch trình hàng ngày ở đâu?', pronunciation: '토이 코 테 녠 릭 쯔엉 항 응아이 어 더우?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: 'Tôi muốn đặt tour bờ biển này', pronunciation: '토이 무온 닷 투어 보 비엔 나이', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: 'Điểm hẹn cho tour ở đâu?', pronunciation: '디엠 헨 초 투어 어 더우?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: 'Làm thế nào để kết nối Wi-Fi?', pronunciation: '람 테 나오 데 켓 노이 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: 'Cái này có được bao gồm (miễn phí) không?', pronunciation: '까이 나이 코 독 바오 꾸옴 (미엔 피) 콩?', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: 'Làm ơn dọn dẹp phòng của tôi', pronunciation: '람 언 존 뎁 퐁 꾸아 토이', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: 'Két sắt trong phòng tôi không hoạt động', pronunciation: '켓 삿 쫑 퐁 토이 콩 호앗 동', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: 'Thang máy gần nhất ở đâu?', pronunciation: '탕 마이 간 느엣 어 더우?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: 'Bạn có nói tiếng Anh không?', pronunciation: '(반 코 노이 티엥 안 콩?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: 'Nhà vệ sinh ở đâu?', pronunciation: '(냐 베 신 어 더우?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: 'Tôi có thể thử được không?', pronunciation: '(토이 코 테 투 독 콩?)', emoji: '👕' },
      { ko: '감사합니다', target: 'Cảm ơn', pronunciation: '(깜 언)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: 'Xin nói chậm lại', pronunciation: '(신 노이 참 라이)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
