import type { PhraseCategory } from './types';

const phrases: PhraseCategory[] = [
  {
    id: 'airport',
    name: '공항 및 비행',
    emoji: '✈️',
    phrases: [
      { ko: '체크인 카운터는 어디에 있나요?', target: '辦理登機手續的櫃檯在哪裡？', pronunciation: '(반리 등기 쇼우슈 더 궤이타이 짜이 나리?)', emoji: '✈️' },
      { ko: '창가 좌석으로 부탁드려요', target: '請給我靠窗的座位', pronunciation: '(칭 게이 워 카오 촹 더 쭤웨이)', emoji: '🪟' },
      { ko: '추가 수하물 요금은 얼마인가요?', target: '托運行李的額外費用是多少？', pronunciation: '(투어윈 싱리 더 어와이 페이용 스 두어샤오?)', emoji: '💼' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소(호텔)',
    emoji: '🏨',
    phrases: [
      { ko: '(이름)으로 예약했어요', target: '我用(名字)預訂了', pronunciation: '(워 용 (이름) 위딩러)', emoji: '📋' },
      { ko: '수건 하나 더 주시겠어요?', target: '可以再給我一條毛巾嗎？', pronunciation: '(커이 짜이 게이 워 이 탸오 마오진 마?)', emoji: '🧺' },
      { ko: '조식은 몇 시에 제공되나요?', target: '早餐幾點提供？', pronunciation: '(자오찬 지디엔 티공?)', emoji: '🍽️' },
      { ko: '체크아웃 후에 짐을 좀 맡아주실 수 있나요?', target: '退房後可以幫我保管行李嗎？', pronunciation: '(투이팡 호우 커이 방 워 바오관 싱리 마?)', emoji: '🧳' },
      { ko: '체크인 시간보다 일찍 도착했는데 짐 맡아주실 수 있나요?', target: '我在入住時間之前到達，可以幫我保管行李嗎？', pronunciation: '(워 짜이 루주 스지엔 즈치엔 다오다, 커이 방 워 바오관 싱리 마?)', emoji: '🕐' },
      { ko: '제 방에서 와이파이가 작동하지 않아요', target: '我房間裡的Wi-Fi不工作', pronunciation: '(워 팡젠 리더 와이파이 부 공쭈어)', emoji: '📶' },
      { ko: '에어컨이 작동하지 않아요', target: '空調不工作', pronunciation: '(콩탸오 부 공쭈어)', emoji: '❄️' },
      { ko: '온수가 나오지 않아요', target: '沒有熱水', pronunciation: '(메이요우 러슈이)', emoji: '🚿' },
      { ko: '체크아웃을 좀 늦게 할 수 있을까요?', target: '可以延遲退房嗎？', pronunciation: '(커이 옌츠 투이팡 마?)', emoji: '🕐' },
      { ko: '택시 한 대 불러주시겠어요?', target: '可以幫我叫一輛計程車嗎？', pronunciation: '(커이 방 워 쟈오 이 량 지청처 마?)', emoji: '🚕' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당/음식',
    emoji: '🍽️',
    phrases: [
      { ko: '메뉴판 좀 보여주시겠어요?', target: '可以看看菜單嗎？', pronunciation: '(커이 칸칸 차이단 마?)', emoji: '📋' },
      { ko: '이걸로 주문할게요', target: '我想點(食物名稱)', pronunciation: '(워 샹 디엔 (음식 이름))', emoji: '🍴' },
      { ko: '물 좀 주세요', target: '請給我水', pronunciation: '(칭 게이 워 슈이)', emoji: '💧' },
      { ko: '계산서 주세요', target: '請給我帳單', pronunciation: '(칭 게이 워 장단)', emoji: '💳' },
      { ko: '여기서 가장 인기 있는 메뉴가 무엇인가요?', target: '這裡最受歡迎的菜是什麼？', pronunciation: '(쩌리 쭈이 쇼우 환잉 더 차이 스 션머?)', emoji: '⭐' },
      { ko: '무엇을 추천하시겠어요?', target: '您推薦什麼？', pronunciation: '(닌 투이지엔 션머?)', emoji: '👍' },
      { ko: '저는 견과류 알레르기가 있어요', target: '我對堅果過敏', pronunciation: '(워 뚜이 지엔구어 구어민)', emoji: '⚠️' },
      { ko: '이거 땅콩 들어있나요?', target: '這裡面有花生嗎？', pronunciation: '(쩌 리미엔 요우 화셩 마?)', emoji: '🥜' },
      { ko: '이거 포장해 갈 수 있을까요?', target: '可以打包帶走嗎？', pronunciation: '(커이 다바오 다이조우 마?)', emoji: '📦' },
      { ko: '계산서 따로 주시겠어요?', target: '可以分開結帳嗎？', pronunciation: '(커이 펀카이 지에장 마?)', emoji: '🧾' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑/결제',
    emoji: '🛍️',
    phrases: [
      { ko: '이거 얼마에요?', target: '這個多少錢？', pronunciation: '(쩌거 두어샤오 치엔?)', emoji: '💰' },
      { ko: '이거 다른 사이즈 있나요?', target: '這個有其他尺寸嗎？', pronunciation: '(쩌거 요우 치타 츠춘 마?)', emoji: '📏' },
      { ko: '카드로 결제할 수 있나요?', target: '可以用卡付款嗎？', pronunciation: '(커이 용 카 푸콴 마?)', emoji: '💳' },
      { ko: '환불 가능할까요?', target: '可以退款嗎？', pronunciation: '(커이 투이콴 마?)', emoji: '↩️' },
    ],
  },
  {
    id: 'transport',
    name: '길찾기/교통',
    emoji: '🚌',
    phrases: [
      { ko: '버스 정류장이 어디 있나요?', target: '請問公車站在哪裡？', pronunciation: '(칭원 공처잔 짜이 나리?)', emoji: '🚏' },
      { ko: '역에 어떻게 가나요?', target: '怎麼去車站？', pronunciation: '(전머 취 처잔?)', emoji: '🚇' },
      { ko: '멀리 있나요?', target: '遠嗎？', pronunciation: '(위엔 마?)', emoji: '📍' },
      { ko: '지도 받을 수 있나요?', target: '可以給我地圖嗎？', pronunciation: '(커이 게이 워 디투 마?)', emoji: '🗺️' },
      { ko: '가장 가까운 지하철역이 어디인가요?', target: '最近的地鐵站在哪裡？', pronunciation: '(쭈이진 더 디티에잔 짜이 나리?)', emoji: '🚇' },
    ],
  },
  {
    id: 'tourism',
    name: '관광/티켓',
    emoji: '🎫',
    phrases: [
      { ko: '성인 2명, 아이 1명 주세요', target: '請給我2個成人和1個兒童的票', pronunciation: '(칭 게이 워 량 거 청런 허 이 거 얼통 더 퍄오)', emoji: '👨‍👩‍👧' },
      { ko: '몇 시에 문 여나요?', target: '幾點開門？', pronunciation: '(지디엔 카이먼?)', emoji: '🕐' },
      { ko: '몇 시에 문 닫나요?', target: '幾點關門？', pronunciation: '(지디엔 관먼?)', emoji: '🕐' },
      { ko: '여기서 사진 찍어도 되나요?', target: '這裡可以拍照嗎？', pronunciation: '(쩌리 커이 파이자오 마?)', emoji: '📷' },
    ],
  },
  {
    id: 'emergency',
    name: '병원/긴급',
    emoji: '🏥',
    phrases: [
      { ko: '몸이 좋지 않아요', target: '我身體不舒服', pronunciation: '(워 션티 부 슈푸)', emoji: '😷' },
      { ko: '의사가 필요합니다', target: '我需要醫生', pronunciation: '(워 쉬야오 이셩)', emoji: '👨‍⚕️' },
      { ko: '두통이 있어요', target: '我頭痛', pronunciation: '(워 토우통)', emoji: '🤕' },
      { ko: '경찰을 불러주세요', target: '請叫警察', pronunciation: '(칭 쟈오 징차)', emoji: '🚨' },
      { ko: '제 여권을 잃어버린 것 같아요', target: '我好像丟了護照', pronunciation: '(워 하오샹 뎌우러 후자오)', emoji: '📕' },
      { ko: '제 지갑을 잃어버린 것 같아요', target: '我好像丟了錢包', pronunciation: '(워 하오샹 뎌우러 치엔바오)', emoji: '👛' },
      { ko: '제 휴대폰을 잃어버린 것 같아요', target: '我好像丟了手機', pronunciation: '(워 하오샹 뎌우러 쇼우지)', emoji: '📱' },
      { ko: '분실물 센터가 어디인가요?', target: '失物招領處在哪裡？', pronunciation: '(스우 자오링추 짜이 나리?)', emoji: '🔍' },
      { ko: '여기에 좀 적어주시겠어요?', target: '可以幫我寫下來嗎？', pronunciation: '(커이 방 워 시에시아라이 마?)', emoji: '✍️' },
      { ko: '조금만 더 천천히 말해주세요', target: '請再慢一點說', pronunciation: '(칭 짜이 만 이디엔 슈어)', emoji: '🗣️' },
      { ko: '가장 가까운 약국이 어디인가요?', target: '最近的藥局在哪裡？', pronunciation: '(쭈이진 더 야오쥐 짜이 나리?)', emoji: '🏥' },
      { ko: '두통에 먹을 약이 필요해요', target: '我需要頭痛藥', pronunciation: '(워 쉬야오 토우통 야오)', emoji: '🤕' },
      { ko: '복통에 먹을 약이 필요해요', target: '我需要胃痛藥', pronunciation: '(워 쉬야오 웨이통 야오)', emoji: '😣' },
      { ko: '감기약이 필요해요', target: '我需要感冒藥', pronunciation: '(워 쉬야오 간마오 야오)', emoji: '🤒' },
      { ko: '일회용 반창고 있나요?', target: '有創可貼嗎？', pronunciation: '(요우 촹커티에 마?)', emoji: '🩹' },
    ],
  },
  {
    id: 'cruise',
    name: '크루즈 (왕초보)',
    emoji: '🚢',
    phrases: [
      { ko: '제 방은 어디인가요?', target: '我的客房在哪裡？', pronunciation: '워더 커팡 짜이 나리?', emoji: '🚪' },
      { ko: '제 짐이 아직 안 왔어요', target: '我的行李還沒有到', pronunciation: '워더 싱리 하이 메이요우 다오', emoji: '🧳' },
      { ko: '안전 교육은 어디서 하나요?', target: '安全演習在哪裡？', pronunciation: '안취엔 옌시 짜이 나리?', emoji: '🆘' },
      { ko: '몇 시까지 배로 돌아와야 하나요?', target: '我必須幾點回到船上？', pronunciation: '워 비쉬 지디엔 후이다오 촨샹?', emoji: '⏰' },
      { ko: '지금 배 시간은 몇 시예요?', target: '現在的船上時間是幾點？', pronunciation: '시엔짜이 더 촨샹 스지엔 스 지디엔?', emoji: '🕒' },
      { ko: '의무실은 어디인가요?', target: '醫務室在哪裡？', pronunciation: '이우스 짜이 나리?', emoji: '🏥' },
      { ko: '멀미약 좀 주시겠어요?', target: '能給我一些暈船藥嗎？', pronunciation: '넝 게이 워 이씨에 윈촨 야오 마?', emoji: '🤢' },
      { ko: '객실 키(선내 카드)를 잃어버렸어요', target: '我的房卡(船卡)丟了', pronunciation: '워더 팡카 (촨카) 띠우러', emoji: '💳' },
      { ko: '뷔페 식당은 어디인가요?', target: '自助餐廳在哪裡？', pronunciation: '쯔주 찬팅 짜이 나리?', emoji: '🍔' },
      { ko: '제 저녁 식사 시간/테이블은 어디죠?', target: '我的晚餐時間和桌號是？', pronunciation: '워더 완찬 스지엔 허 쭈어하오 스?', emoji: '🍽️' },
      { ko: '룸서비스 주문할 수 있나요?', target: '可以叫客房服務嗎？', pronunciation: '커이 쟈오 커팡 푸우 마?', emoji: '🛎️' },
      { ko: '이 (이탈리안) 식당을 예약하고 싶어요', target: '我想預訂(義大利)餐廳', pronunciation: '워 샹 위딩 (이탈리) 찬팅', emoji: '🗓️' },
      { ko: '오늘의 일정표는 어디서 받나요?', target: '在哪裡拿每日日程表？', pronunciation: '짜이 나리 나 메이르 르청뱌오?', emoji: '📰' },
      { ko: '이 기항지 관광을 예약하고 싶어요', target: '我想預訂這個岸上觀光', pronunciation: '워 샹 위딩 쩌거 안샹 관광', emoji: '🗺️' },
      { ko: '관광 모임 장소는 어디인가요?', target: '旅遊團的集合點在哪裡？', pronunciation: '뤼요우투안 더 지허디엔 짜이 나리?', emoji: '📍' },
      { ko: '와이파이 어떻게 연결해요?', target: '怎麼連接Wi-Fi？', pronunciation: '전머 리엔지에 와이파이?', emoji: '📶' },
      { ko: '이건 무료인가요?', target: '這個是免費的嗎？(包括嗎？)', pronunciation: '쩌거 스 미엔페이 더 마? (바오쿠어 마?)', emoji: '💸' },
      { ko: '제 객실을 청소해주세요', target: '請打掃我的房間', pronunciation: '칭 다사오 워더 팡지엔', emoji: '🧹' },
      { ko: '방 금고가 작동하지 않아요', target: '房間裡的保險箱打不開', pronunciation: '팡지엔 리더 바오시엔샹 다부카이', emoji: '🔒' },
      { ko: '가장 가까운 엘리베이터는 어디죠?', target: '最近的電梯在哪裡？', pronunciation: '쭈이진 더 디엔티 짜이 나리?', emoji: '↕️' },
    ],
  },
  {
    id: 'essential',
    name: '기타 필수 표현',
    emoji: '💬',
    phrases: [
      { ko: '영어 하실 줄 아세요?', target: '你會說英語嗎？', pronunciation: '(니 후이 슈어 잉위 마?)', emoji: '🗣️' },
      { ko: '화장실이 어디인가요?', target: '洗手間在哪裡？', pronunciation: '(시쇼우지엔 짜이 나리?)', emoji: '🚻' },
      { ko: '이거 입어봐도 될까요?', target: '可以試穿嗎？', pronunciation: '(커이 스촨 마?)', emoji: '👕' },
      { ko: '감사합니다', target: '謝謝', pronunciation: '(씨에씨에)', emoji: '🙏' },
      { ko: '천천히 말해주세요', target: '請慢點說', pronunciation: '(칭 만 디엔 슈어)', emoji: '🗣️' },
    ],
  },
];

export default phrases;
