export const dynamic = 'force-dynamic';

// app/api/public/landing-pages/[slug]/comments/[commentId]/route.ts
// 랜딩페이지 댓글 수정/삭제 API

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getSessionUser } from '@/lib/auth';
import { SESSION_COOKIE } from '@/lib/auth';

/**
 * PUT: 댓글 수정 (비밀번호 인증 필요)
 */
export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string; commentId: string }> | { slug: string; commentId: string } }
) {
  try {
    const resolvedParams = await Promise.resolve(params);
    const slug = resolvedParams.slug;
    const commentId = parseInt(resolvedParams.commentId);

    if (isNaN(commentId)) {
      return NextResponse.json(
        { ok: false, error: '잘못된 댓글 ID입니다.' },
        { status: 400 }
      );
    }

    // 랜딩페이지 조회
    const landingPage = await prisma.landingPage.findFirst({
      where: {
        OR: [
          { slug },
          { id: isNaN(Number(slug)) ? -1 : Number(slug) },
        ],
        isActive: true,
        isPublic: true,
        commentEnabled: true,
      },
    });

    if (!landingPage) {
      return NextResponse.json(
        { ok: false, error: '랜딩페이지를 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    // 댓글 조회
    const comment = await prisma.landingPageComment.findFirst({
      where: {
        id: commentId,
        landingPageId: landingPage.id,
      },
    });

    if (!comment) {
      return NextResponse.json(
        { ok: false, error: '댓글을 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    // AI 생성 댓글은 수정 불가
    if (comment.isAutoGenerated) {
      return NextResponse.json(
        { ok: false, error: 'AI 생성 댓글은 수정할 수 없습니다.' },
        { status: 403 }
      );
    }

    const body = await req.json();
    const { content, password } = body;

    if (!content || content.trim().length === 0) {
      return NextResponse.json(
        { ok: false, error: '댓글 내용을 입력해주세요.' },
        { status: 400 }
      );
    }

    // 비밀번호 확인
    if (!password || password.trim().length === 0) {
      return NextResponse.json(
        { ok: false, error: '비밀번호를 입력해주세요.' },
        { status: 400 }
      );
    }

    // 비밀번호 검증 (metadata에서 확인)
    const crypto = await import('crypto');
    const hashedPassword = crypto.createHash('sha256').update(password.trim()).digest('hex');
    
    // metadata에서 비밀번호 확인
    let passwordMatch = false;
    if (comment.metadata && typeof comment.metadata === 'object' && 'password' in comment.metadata) {
      passwordMatch = (comment.metadata as any).password === hashedPassword;
    }

    if (!passwordMatch) {
      return NextResponse.json(
        { ok: false, error: '비밀번호가 일치하지 않습니다.' },
        { status: 401 }
      );
    }

    // 댓글 수정
    const updatedComment = await prisma.landingPageComment.update({
      where: { id: commentId },
      data: {
        content: content.trim(),
      },
    });

    return NextResponse.json({
      ok: true,
      comment: {
        id: updatedComment.id,
        authorName: updatedComment.authorName,
        content: updatedComment.content,
        createdAt: updatedComment.createdAt.toISOString(),
      },
    });
  } catch (error: any) {
    console.error('[Landing Page Comment Update] Error:', error);
    return NextResponse.json(
      {
        ok: false,
        error: error.message || '댓글 수정 중 오류가 발생했습니다.',
      },
      { status: 500 }
    );
  }
}

/**
 * DELETE: 댓글 삭제 (관리자/대리점장만 가능 또는 비밀번호 인증)
 */
export async function DELETE(
  req: NextRequest,
  { params }: { params: Promise<{ slug: string; commentId: string }> | { slug: string; commentId: string } }
) {
  try {
    const resolvedParams = await Promise.resolve(params);
    const slug = resolvedParams.slug;
    const commentId = parseInt(resolvedParams.commentId);

    if (isNaN(commentId)) {
      return NextResponse.json(
        { ok: false, error: '잘못된 댓글 ID입니다.' },
        { status: 400 }
      );
    }

    // 랜딩페이지 조회 (adminId 포함)
    const landingPage = await prisma.landingPage.findFirst({
      where: {
        OR: [
          { slug },
          { id: isNaN(Number(slug)) ? -1 : Number(slug) },
        ],
        isActive: true,
        isPublic: true,
      },
      select: {
        id: true,
        adminId: true,
      },
    });

    if (!landingPage) {
      return NextResponse.json(
        { ok: false, error: '랜딩페이지를 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    // 댓글 조회
    const comment = await prisma.landingPageComment.findFirst({
      where: {
        id: commentId,
        landingPageId: landingPage.id,
      },
    });

    if (!comment) {
      return NextResponse.json(
        { ok: false, error: '댓글을 찾을 수 없습니다.' },
        { status: 404 }
      );
    }

    // 세션 확인 (관리자/대리점장 체크) - 먼저 권한 확인 (절대 중요!)
    // 대리점장이 만든 랜딩페이지의 댓글 삭제 시 비밀번호 절대 요구하지 않음
    const sid = req.cookies.get(SESSION_COOKIE)?.value;
    let isAdminOrManager = false;
    let currentUserId: number | null = null;
    
    if (sid) {
      try {
        const session = await prisma.session.findUnique({
          where: { id: sid },
          include: {
            User: {
              select: {
                id: true,
                role: true,
                name: true,
                email: true,
              },
            },
          },
        });

        if (session?.User) {
          currentUserId = session.User.id;
          
          // boss로 시작하는 사용자 ID/이름 체크
          const userName = session.User.name || '';
          const userEmail = session.User.email || '';
          const isBossUser = userName.toLowerCase().startsWith('boss') || userEmail.toLowerCase().startsWith('boss');
          
          // boss 사용자는 모든 랜딩페이지의 댓글 삭제 가능 (비밀번호 불필요)
          if (isBossUser) {
            console.log('[Landing Page Comment Delete] Boss user detected, allowing delete without password');
            isAdminOrManager = true;
          }
          // 관리자인 경우 - 모든 랜딩페이지의 댓글 삭제 가능 (비밀번호 절대 불필요!)
          else if (session.User.role === 'admin') {
            console.log('[Landing Page Comment Delete] Admin user detected, allowing delete without password (all landing pages)');
            isAdminOrManager = true;
          } else if (session.User.role === 'partner') {
            // 대리점장인지 확인 (AffiliateProfile 확인)
            const profile = await prisma.affiliateProfile.findUnique({
              where: { userId: session.User.id },
              select: { type: true },
            });
            
            console.log('[Landing Page Comment Delete] Partner check:', {
              userId: session.User.id,
              profileType: profile?.type,
              landingPageAdminId: landingPage.adminId,
              isBranchManager: profile?.type === 'BRANCH_MANAGER',
              isOwner: landingPage.adminId === session.User.id,
            });
            
            // 대리점장은 본인이 만든 랜딩페이지의 모든 댓글 삭제 가능 (비밀번호 절대 불필요!)
            if (profile?.type === 'BRANCH_MANAGER') {
              // 대리점장은 자신의 랜딩페이지의 댓글만 삭제 가능
              if (landingPage.adminId === session.User.id) {
                console.log('[Landing Page Comment Delete] Branch manager owner detected, allowing delete without password');
                isAdminOrManager = true;
              } else {
                console.log('[Landing Page Comment Delete] Branch manager detected but not owner, checking...');
                // 자신의 랜딩페이지가 아니면 삭제 불가
              }
            }
          }
        }
      } catch (error) {
        console.error('[Landing Page Comment Delete] Session check error:', error);
        // 세션 확인 실패는 무시 (일반 유저로 처리)
      }
    }

    // 관리자/대리점장/boss인 경우 비밀번호 없이 바로 삭제 가능 (절대 비밀번호 요구하지 않음!)
    if (isAdminOrManager) {
      // 비밀번호 확인 절차 완전히 건너뛰기
      await prisma.landingPageComment.delete({
        where: { id: commentId },
      });

      return NextResponse.json({
        ok: true,
        message: '댓글이 삭제되었습니다.',
      });
    }

    // 관리자/대리점장이 아닌 경우 본인 댓글인지 확인
    // 요청 본문에서 비밀번호 확인 (일반 유저용만 - 대리점장은 이미 위에서 처리됨)
    const body = await req.json().catch(() => ({}));
    const { password } = body;
    
    // 댓글 작성자 ID 확인
    let commentAuthorId: number | null = null;
    if (comment.metadata && typeof comment.metadata === 'object' && 'userId' in comment.metadata) {
      commentAuthorId = (comment.metadata as any).userId;
    }

    // 본인 댓글이 아닌 경우 삭제 불가
    if (commentAuthorId !== null && currentUserId !== commentAuthorId) {
      return NextResponse.json(
        { ok: false, error: '본인의 댓글만 삭제할 수 있습니다.' },
        { status: 403 }
      );
    }

    // 본인 댓글이거나 비회원 댓글인 경우 비밀번호 확인 필요 (대리점장은 절대 여기 도달하지 않음)
    if (!password || password.trim().length === 0) {
      return NextResponse.json(
        { ok: false, error: '비밀번호를 입력해주세요.' },
        { status: 400 }
      );
    }

    // 비밀번호 검증 (metadata에서 확인)
    const crypto = await import('crypto');
    const hashedPassword = crypto.createHash('sha256').update(password.trim()).digest('hex');
    
    // metadata에서 비밀번호 확인
    let passwordMatch = false;
    if (comment.metadata && typeof comment.metadata === 'object' && 'password' in comment.metadata) {
      passwordMatch = (comment.metadata as any).password === hashedPassword;
    }

    if (!passwordMatch) {
      return NextResponse.json(
        { ok: false, error: '비밀번호가 일치하지 않습니다.' },
        { status: 401 }
      );
    }

    // 일반 사용자: 비밀번호 확인 후 삭제
    await prisma.landingPageComment.delete({
      where: { id: commentId },
    });

    return NextResponse.json({
      ok: true,
      message: '댓글이 삭제되었습니다.',
    });
  } catch (error: any) {
    console.error('[Landing Page Comment Delete] Error:', error);
    return NextResponse.json(
      {
        ok: false,
        error: error.message || '댓글 삭제 중 오류가 발생했습니다.',
      },
      { status: 500 }
    );
  }
}
